export function createUI(W,R,D,E,C,A,settings,saveSettings){
 const style=document.createElement('style');style.textContent=`
 #hud{max-width:270px;padding:7px 9px;font-size:11px;background:#07121bb8;border-color:#ffffff24}#cam,#controls{display:none}
 #v10Menu{position:fixed;z-index:70;right:10px;top:max(10px,env(safe-area-inset-top));width:42px;height:36px;min-width:42px;padding:0;border-radius:10px;background:#07121be0;border:1px solid #ffffff30;font-size:18px}
 #v10Drawer{display:none;position:fixed;z-index:65;right:10px;top:max(54px,calc(env(safe-area-inset-top) + 44px));width:min(90vw,360px);max-height:78vh;overflow:hidden;background:#07121bf0;border:1px solid #ffffff2c;border-radius:14px;backdrop-filter:blur(12px);box-shadow:0 10px 32px #0007}#v10Drawer.open{display:block}
 #v10Tabs{display:flex;gap:4px;padding:7px;overflow-x:auto;border-bottom:1px solid #ffffff18}#v10Tabs button{height:31px;min-width:48px;padding:0 7px;font-size:9px;border-radius:7px;white-space:nowrap}#v10Tabs button.on{background:#fff;color:#07121b}
 #v10Body{max-height:calc(78vh - 46px);overflow:auto;padding:8px;font-size:10px;line-height:1.4}.head{display:flex;justify-content:space-between;font-weight:950;margin-bottom:5px}.row{display:grid;grid-template-columns:22px 1fr 46px 40px;gap:4px;align-items:center;padding:5px 3px;border-top:1px solid #ffffff12;border-radius:5px}.row.tap{cursor:pointer}.row.tap:active{background:#ffffff1c}.row.me{color:#65ff9a;background:#65ff9a0b}.muted{color:#aeb8c0}.good{color:#65ff9a}.warn{color:#ffd35f}.bad{color:#ff7373}.section{padding:7px 0;border-top:1px solid #ffffff16}.section:first-child{border-top:0}.section b{color:#fff}.tag{display:inline-block;padding:2px 5px;border-radius:5px;background:#ffffff14;margin:1px 2px 1px 0;font-size:9px;font-weight:850}.modegrid{display:grid;grid-template-columns:repeat(3,1fr);gap:5px}.modegrid button,.action{height:34px;min-width:0;padding:0 6px;font-size:9px}.modegrid button.on{background:#fff;color:#07121b}.controls3{display:grid;grid-template-columns:repeat(3,1fr);gap:5px}.controls3 button{height:34px;min-width:0}
 #trackMap{width:100%;aspect-ratio:1.42;background:#081017;border-radius:10px;border:1px solid #ffffff18;touch-action:manipulation}.setting{display:grid;grid-template-columns:1fr 1.2fr;gap:8px;align-items:center;padding:5px 0}.setting select,.setting input{width:100%;background:#101b24;color:#fff;border:1px solid #ffffff25;border-radius:7px;height:32px;padding:0 6px}.range{width:100%}.apply{width:100%;height:38px;margin-top:8px;background:#fff;color:#07121b;border:0;border-radius:8px;font-weight:950}
 #eventBanner{position:fixed;z-index:62;top:max(58px,calc(env(safe-area-inset-top) + 52px));left:50%;transform:translateX(-50%);padding:7px 13px;border-radius:8px;background:#0b121ce8;border:1px solid #ffffff38;font-size:12px;font-weight:950;letter-spacing:.5px;opacity:0;transition:opacity .15s;white-space:nowrap;pointer-events:none}#eventBanner.show{opacity:1}#eventBanner.yellow{background:#8a6a00ed}#eventBanner.sc{background:#9a6d00ed}#eventBanner.fault{background:#8d2020ed}
 @media(max-width:430px){#v10Drawer{width:calc(100vw - 20px)}}
 `;document.head.appendChild(style);
 const menu=document.createElement('button');menu.id='v10Menu';menu.textContent='☰';document.body.appendChild(menu);
 const drawer=document.createElement('div');drawer.id='v10Drawer';drawer.innerHTML='<div id="v10Tabs"><button data-v="race" class="on">RACE</button><button data-v="map">MAP</button><button data-v="data">DATA</button><button data-v="series">SERIES</button><button data-v="radio">RADIO</button><button data-v="stats">STATS</button><button data-v="settings">SET</button><button data-v="cam">CAM</button></div><div id="v10Body"></div>';document.body.appendChild(drawer);
 const tabs=drawer.querySelector('#v10Tabs'),body=drawer.querySelector('#v10Body');const banner=document.createElement('div');banner.id='eventBanner';document.body.appendChild(banner);
 let opened=false,view='race',focusId=0,acc=0,mapCanvas=null,mapCars=[];
 function close(){opened=false;drawer.classList.remove('open');menu.textContent='☰';}
 menu.onclick=()=>{opened=!opened;drawer.classList.toggle('open',opened);menu.textContent=opened?'×':'☰';if(opened)render(true);};
 tabs.onclick=e=>{const b=e.target.closest('[data-v]');if(!b)return;view=b.dataset.v;tabs.querySelectorAll('button').forEach(x=>x.classList.toggle('on',x===b));render(true);};
 const fmt=t=>!Number.isFinite(t)?'--':`${Math.floor(t/60)}:${(t%60).toFixed(3).padStart(6,'0')}`,fmtS=t=>!Number.isFinite(t)?'--':`${t.toFixed(3)}s`,colour=n=>`#${(n>>>0).toString(16).padStart(6,'0')}`,tyreColor=c=>R.compounds?.[c]?.color||'#fff';
 const track=[];for(let i=0;i<220;i++){const p=W.sample(W.total*i/220).p;track.push([p.x,p.z]);}const xs=track.map(p=>p[0]),zs=track.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minZ=Math.min(...zs),maxZ=Math.max(...zs);
 function mapPoint(x,z,w,h){const pad=18,s=Math.min((w-pad*2)/(maxX-minX),(h-pad*2)/(maxZ-minZ));return[pad+(x-minX)*s,h-pad-(z-minZ)*s];}
 function drawMap(){if(!mapCanvas)return;const dpr=Math.min(devicePixelRatio||1,2),w=Math.max(260,mapCanvas.getBoundingClientRect().width),h=w/1.42;mapCanvas.width=w*dpr;mapCanvas.height=h*dpr;const g=mapCanvas.getContext('2d');g.setTransform(dpr,0,0,dpr,0,0);g.clearRect(0,0,w,h);g.lineJoin='round';g.lineCap='round';g.strokeStyle='#2a333a';g.lineWidth=7;g.beginPath();track.forEach(([x,z],i)=>{const [px,py]=mapPoint(x,z,w,h);i?g.lineTo(px,py):g.moveTo(px,py)});g.closePath();g.stroke();g.strokeStyle='#b8c0c4';g.lineWidth=2;g.stroke();for(const [a,b] of R.drsZones||[]){g.strokeStyle='#54df79';g.lineWidth=4;g.beginPath();for(let k=0;k<=24;k++){const f=a+(b-a)*k/24,p=W.sample(W.total*(f>=1?f-1:f)).p,[x,y]=mapPoint(p.x,p.z,w,h);k?g.lineTo(x,y):g.moveTo(x,y);}g.stroke();}mapCars=[];for(const c of R.cars){if(c.retired)continue;const p=c.mesh.position,[x,y]=mapPoint(p.x,p.z,w,h);mapCars.push({id:c.id,x,y});g.beginPath();g.fillStyle=colour(c.teamColor||0xffffff);g.arc(x,y,c.id===focusId?5.2:3.7,0,Math.PI*2);g.fill();if(c.id===focusId){g.strokeStyle='#fff';g.lineWidth=1.5;g.stroke();}}}
 function follow(id){focusId=Number(id);C.setFocus(focusId);A?.setFocus?.(focusId);close();}
 function raceHTML(){const st=R.getStandings(),lead=st[0],lap=Math.min(Math.max(1,(lead?.lap||0)+1),R.race.lapsTarget),phase=R.sessionPhase;let h=`<div class="head"><span>${phase==='QUALIFYING'?'QUALIFYING':phase==='FORMATION'?'FORMATION LAP':`LAP ${lap}/${R.race.lapsTarget}`}</span><span>${R.flag}</span></div>`;if(phase==='QUALIFYING'){R.qualifying.forEach((q,i)=>{const c=R.cars[q.carId];h+=`<div class="row tap ${c.id===focusId?'me':''}" data-car="${c.id}"><b>${i+1}</b><span>${c.name}<br><span class="muted">${c.team}</span></span><span>${q.time.toFixed(3)}</span><span>Q</span></div>`;});return h;}st.forEach(c=>{const gap=c===lead?'LEAD':`+${Math.max(0,((lead._v8Progress??0)-(c._v8Progress??0))/Math.max(1,lead.v)).toFixed(1)}s`;h+=`<div class="row tap ${c.id===focusId?'me':''}" data-car="${c.id}"><b>${c.position}</b><span>${c.name}<br><span class="muted">${c.team} · ${c.type.toUpperCase()}</span></span><span>${gap}</span><span style="color:${tyreColor(c.compound)}">${c.compound[0]}${Math.round(c.wear*100)}</span></div>`;});return h;}
 function dataHTML(){const c=R.cars[focusId]||R.getStandings()[0];if(!c)return'';const gb=R.globalBestSectors||[];return `<div class="section"><b>${c.name} · ${c.team}</b><br>P${c.position} · ${c.type.toUpperCase()} · ${Math.round(c.v*3.6)} km/h<br><span class="tag ${c.drsActive?'good':''}">DRS ${c.drsActive?'ACTIVE':c.drsEligible?'READY':'OFF'}</span><span class="tag">${c.battleState}</span>${c.fault?`<span class="tag bad">${c.fault}</span>`:''}${c.penaltySeconds?`<span class="tag bad">+${c.penaltySeconds}s</span>`:''}</div><div class="section"><b>TEMPERATURE</b><br>TYRE ${Math.round(c.tyreTemp)}°C · BRAKE ${Math.round(c.brakeTemp)}°C · GRIP ${Math.round((c.tempGrip||1)*100)}%</div><div class="section"><b>MACHINE</b><br>POWER ${Math.round(c.machine.power*100)} · AERO ${Math.round(c.machine.aero*100)} · BRAKE ${Math.round(c.machine.brake*100)}<br>TYRE ${Math.round(c.machine.tyre*100)} · REL ${Math.round(c.machine.reliability*1000)/10}%</div><div class="section"><b>SECTORS</b><br>S1 ${fmtS(c.lastSectors[0])} <span class="muted">BEST ${fmtS(c.bestSectors[0])} / ${fmtS(gb[0])}</span><br>S2 ${fmtS(c.lastSectors[1])} <span class="muted">BEST ${fmtS(c.bestSectors[1])} / ${fmtS(gb[1])}</span><br>S3 ${fmtS(c.lastSectors[2])} <span class="muted">BEST ${fmtS(c.bestSectors[2])} / ${fmtS(gb[2])}</span><br>LAP BEST ${fmt(c.bestLap)}</div><div class="section"><b>PENALTIES</b><br>TRACK WARN ${c.trackWarnings}/3 · SERVED ${c.penaltiesServed}</div>`;}
 function seriesHTML(){const ch=R.championship;let h=`<div class="section"><b>CHAMPIONSHIP · ROUND ${ch.roundNumber}/${ch.rounds}</b><br>${ch.roundName} · ${W.circuitName}</div><div class="section"><b>DRIVERS</b>`;ch.drivers.slice(0,10).forEach((d,i)=>h+=`<div class="row"><b>${i+1}</b><span>${d.name}<br><span class="muted">${d.team}</span></span><span>${d.points}</span><span>PTS</span></div>`);h+='</div><div class="section"><b>TEAMS</b>';ch.teams.forEach((t,i)=>h+=`<div class="row"><b>${i+1}</b><span style="color:${colour(t.color)}">${t.name}</span><span>${t.points}</span><span>PTS</span></div>`);h+='</div>';if(ch.awarded)h+=`<button class="apply" id="nextRoundBtn">${ch.isFinal?'RESET SEASON':'NEXT ROUND'}</button>`;return h;}
 function radioHTML(){const r=[...(R.radio||[])].reverse();return r.length?r.map(x=>`<div class="section"><b>${x.name}</b> <span class="muted">${x.kind}</span><br>${x.text}</div>`).join(''):'<div class="muted">No radio messages yet.</div>';}
 function statsHTML(){const s=R.historyStats||{history:[],drivers:[]};let h='<div class="section"><b>CAREER STATS</b>';s.drivers.slice(0,10).forEach((d,i)=>h+=`<div class="row"><b>${i+1}</b><span>${d.name}</span><span>${d.wins}W</span><span>${d.podiums}P</span></div>`);h+='</div><div class="section"><b>RECENT RACES</b>';for(const r of s.history.slice(0,8))h+=`<div class="section"><b>${r.circuit}</b> · ${r.winner}<br><span class="muted">POLE ${r.pole} · FL ${r.fastest} · DNF ${(r.dnf||[]).length}</span></div>`;return h+'</div>';}
 function settingsHTML(){return `<div class="section"><b>RACE SETTINGS</b><div class="setting"><span>Circuit</span><select id="setCircuit"><option value="CHAMPIONSHIP">Championship Auto</option><option value="SUZUKA">Suzuka</option><option value="FUJI_STYLE">Fuji Style</option><option value="MONZA_STYLE">Monza Style</option><option value="SPA_STYLE">Spa Style</option></select></div><div class="setting"><span>Laps</span><input id="setLaps" type="number" min="2" max="30" value="${settings.laps}"></div><div class="setting"><span>AI</span><select id="setAI"><option value="0.9">Easy</option><option value="1">Normal</option><option value="1.07">Hard</option><option value="1.14">Expert</option></select></div><div class="setting"><span>Weather</span><select id="setWeather"><option value="DYNAMIC">Dynamic</option><option value="SUNNY">Sunny</option><option value="CLOUDY">Cloudy</option><option value="LIGHT_RAIN">Light Rain</option><option value="RAIN">Rain</option></select></div><div class="setting"><span>Start time</span><input id="setTime" type="number" min="6" max="20" step="0.5" value="${settings.time}"></div><div class="setting"><span>Failures</span><select id="setFail"><option value="0">Off</option><option value="0.5">Low</option><option value="1">Normal</option><option value="2">High</option></select></div><div class="setting"><span>Tyre wear</span><select id="setWear"><option value="0.5">0.5x</option><option value="1">1x</option><option value="1.5">1.5x</option><option value="2">2x</option></select></div><div class="setting"><span>Safety Car</span><select id="setSC"><option value="1">On</option><option value="0">Off</option></select></div><button class="apply" id="applySettings">APPLY & RESTART</button></div>`;}
 function camHTML(){const modes=['AUTO','TV','CHASE','HELI','COCKPIT','NOSE','REAR','WHEEL','BUMPER','PHOTO'];return `<div class="section"><b>CAMERA · ${C.mode}</b><div class="modegrid">${modes.map(m=>`<button data-cam="${m}" class="${C.mode===m?'on':''}">${m}</button>`).join('')}</div></div><div class="section"><b>ZOOM</b><div class="controls3"><button data-act="zin">＋</button><button data-act="zout">−</button><button data-act="reset">↺</button></div></div><div class="section"><b>PHOTO MODE</b><div class="controls3"><button data-pan="0,2,0">UP</button><button data-pan="0,0,8">FWD</button><button data-pan="0,-2,0">DOWN</button><button data-pan="-8,0,0">LEFT</button><button data-pan="0,0,-8">BACK</button><button data-pan="8,0,0">RIGHT</button></div><br>FOV <input id="fovRange" class="range" type="range" min="25" max="90" value="50"><br>Exposure <input id="expRange" class="range" type="range" min="0.5" max="1.6" step="0.05" value="1"></div><div class="section"><button class="apply" id="soundBtn">SOUND ${A?.enabled?'ON':'OFF'}</button><br><span class="muted">1 finger: 360° rotate · 2 fingers: zoom · double tap: reset</span></div>`;}
 function mapHTML(){return'<div class="section"><b>LIVE TRACK MAP</b><br><span class="muted">Tap a car to follow it</span></div><canvas id="trackMap"></canvas><div class="section muted">Green: DRS zones</div>';}
 function render(force=false){if(!opened&&!force)return;body.innerHTML=view==='race'?raceHTML():view==='map'?mapHTML():view==='data'?dataHTML():view==='series'?seriesHTML():view==='radio'?radioHTML():view==='stats'?statsHTML():view==='settings'?settingsHTML():camHTML();if(view==='map'){mapCanvas=body.querySelector('#trackMap');mapCanvas.onclick=e=>{const r=mapCanvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;let best=null,d=1e9;for(const p of mapCars){const q=(p.x-x)**2+(p.y-y)**2;if(q<d){d=q;best=p;}}if(best&&d<625)follow(best.id);};requestAnimationFrame(drawMap);}else mapCanvas=null;if(view==='settings'){const set=(id,val)=>{const x=body.querySelector(id);if(x)x.value=String(val)};set('#setCircuit',settings.circuit);set('#setAI',settings.ai);set('#setWeather',settings.weather);set('#setFail',settings.failures);set('#setWear',settings.tyreWear);set('#setSC',settings.safetyCar?1:0);}}
 drawer.addEventListener('click',async e=>{const row=e.target.closest('[data-car]');if(row){follow(row.dataset.car);return;}const cam=e.target.closest('[data-cam]');if(cam){C.setMode(cam.dataset.cam);render(true);return;}const pan=e.target.closest('[data-pan]');if(pan){C.panPhoto(...pan.dataset.pan.split(',').map(Number));return;}const act=e.target.closest('[data-act]');if(act){if(act.dataset.act==='zin')C.zoomIn();else if(act.dataset.act==='zout')C.zoomOut();else C.reset();return;}if(e.target.id==='soundBtn'){await A?.toggle?.();render(true);return;}if(e.target.id==='nextRoundBtn'){R.nextRound();return;}if(e.target.id==='applySettings'){const s={...settings,circuit:body.querySelector('#setCircuit').value,laps:Number(body.querySelector('#setLaps').value),ai:Number(body.querySelector('#setAI').value),weather:body.querySelector('#setWeather').value,time:Number(body.querySelector('#setTime').value),failures:Number(body.querySelector('#setFail').value),tyreWear:Number(body.querySelector('#setWear').value),safetyCar:body.querySelector('#setSC').value==='1'};saveSettings(s);location.reload();}});
 drawer.addEventListener('input',e=>{if(e.target.id==='fovRange')C.setFov(e.target.value);if(e.target.id==='expRange')C.setExposure(e.target.value);});
 function update(dt,id){focusId=id;acc+=dt;if(acc<.18)return;acc=0;if(opened)render();let text=D.banner,cls='';if(R.flag==='SC'){text='SAFETY CAR';cls='sc';}else if(R.flag==='YELLOW'){text='YELLOW FLAG';cls='yellow';}else if(text&&(/ENGINE|BRAKE|PUNCTURE|ELECTRICAL|RETIRED|PENALTY/.test(text)))cls='fault';banner.textContent=text||'';banner.className=text?`show ${cls}`:'';if(view==='map'&&opened)requestAnimationFrame(drawMap);}
 return{update};
}
