import {createRace as createV12Race} from './v12-race.js';

export function createRace(W,statusEl,settings={}){
  const R=createV12Race(W,statusEl,settings),baseUpdate=R.update,seen=new Set();
  W.setupGridTheatre?.(R.cars);W.pitCars=R.cars;
  const fuelTypes=new Set(['gt','proto','hyper','lmh','touring','supercar']);
  for(const c of R.cars){c.hybridCharge=1;c.flatSpot=false;c.damageState='OK';c._v13FuelBefore=c.fuel??1;c._pitFailure=null;c._repairAdded=false;c._serviceExtra=false;c._strategyWearRate=.085;}
  function radio(c,text,kind='INFO'){const a=R.radio;if(!a)return;a.push({id:`v13-${Date.now()}-${Math.random()}`,t:R.race.t,carId:c?.id??null,name:c?.name||'RACE CONTROL',text,kind});while(a.length>24)a.shift();}
  function event(type,c,data={}){R.events.push({id:`v13-${Date.now()}-${Math.random()}`,type,t:R.race.t,carId:c?.id??null,data});while(R.events.length>80)R.events.shift();}
  function strategy(c){const lapsLeft=Math.max(0,R.race.lapsTarget-Math.max(0,c.lap||0));const wearRate=Math.max(.035,c._strategyWearRate||.08),life=Math.max(0,(.84-(c.wear||0))/wearRate),need=life<lapsLeft*.82||(W.env?.wetness>.42&&c.compound!=='WET')||(W.env?.wetness<.18&&c.compound==='WET');const st=R.getStandings(),idx=st.indexOf(c),ahead=idx>0?st[idx-1]:null,behind=idx>=0&&idx<st.length-1?st[idx+1]:null;const gapA=ahead?Math.max(0,((ahead._v8Progress??0)-(c._v8Progress??0))/Math.max(1,c.v)):99,gapB=behind?Math.max(0,((c._v8Progress??0)-(behind._v8Progress??0))/Math.max(1,c.v)):99;return{lapsLeft,tyreLifeLaps:life,window:need?'BOX NOW':life<lapsLeft*1.25?'WINDOW OPEN':'STAY OUT',undercut:gapA<3.5&&life<lapsLeft*1.4?'STRONG':'LOW',overcut:gapB<2.5&&c.driver.tireCare>.84?'POSSIBLE':'LOW',fuel:c.fuel??1,charge:c.hybridCharge??1};}
  function onPitEntry(c){if(c._serviceExtra)return;c._serviceExtra=true;const refuel=fuelTypes.has(c.type),extra=refuel?1.15:.72;c.pitTimer=(c.pitTimer||0)+extra;c._pitStopInitial=(c._pitStopInitial||c.pitTimer)+extra;c.pitService=refuel?'REFUEL':'HYBRID CHARGE';const roll=Math.random();if(roll<.018){c._pitFailure='WHEEL NUT';c.pitTimer+=1.35;c._pitStopInitial+=1.35;radio(c,'SLOW STOP · WHEEL NUT','PIT');}else if(roll<.028){c._pitFailure='JACK';c.pitTimer+=1.1;c._pitStopInitial+=1.1;radio(c,'JACK ISSUE · HOLD CAR','PIT');}else if(roll<.034)c._pitFailure='UNSAFE RELEASE';if((c.damage||0)>.12&&!c._repairAdded){const repair=1.0+(c.damage||0)*4.2;c.pitTimer+=repair;c._pitStopInitial+=repair;c._repairAdded=true;c.pitService+=' + REPAIR';radio(c,`DAMAGE REPAIR +${repair.toFixed(1)}s`,'PIT');}}
  function updatePitService(c,dt){if(c.pitState!=='STOP')return;const initial=Math.max(.1,c._pitStopInitial||c.pitTimer||3),p=Math.max(0,Math.min(1,1-(c.pitTimer||0)/initial));if(p>.24&&p<.78){if(fuelTypes.has(c.type))c.fuel=Math.min(1,(c.fuel??0)+dt*.24);else c.hybridCharge=Math.min(1,(c.hybridCharge??0)+dt*.34);}if(c._repairAdded&&p>.45)c.damage=Math.max(0,(c.damage||0)-dt*.22);}
  function finishPit(c,prev){if(prev==='STOP'&&c.pitState!=='STOP'){if(c._pitFailure==='UNSAFE RELEASE'){c.penaltySeconds=(c.penaltySeconds||0)+5;radio(c,'5 SECOND PENALTY · UNSAFE RELEASE','PENALTY');event('PENALTY',c,{reason:'UNSAFE RELEASE',seconds:5});}c._pitFailure=null;c._serviceExtra=false;c._repairAdded=false;}}
  function updateDamage(c){const d=c.damage||0;c.damageState=d>.68?'HEAVY':d>.34?'MODERATE':d>.10?'LIGHT':'OK';W.updateCarDamage?.(c);if(d>.55)c.baseMaxNominal*=.9985;}
  function tyre(c,dt){const old=c._v13WearPrev??c.wear??0,delta=Math.max(0,(c.wear||0)-old);c._v13WearPrev=c.wear;c._strategyWearRate=c._strategyWearRate*.985+delta/Math.max(dt,.001)*80*.015;if((c.brakeVisual||0)>.92&&c.v>24&&Math.random()<dt*.018){c.flatSpot=true;radio(c,'FLAT SPOT SUSPECTED','TYRE');}if(c.pitState==='STOP'&&(c.wear||0)<.08)c.flatSpot=false;W.updateTyreVisual?.(c);}
  function incidents(){for(const e of R.events){if(seen.has(e.id))continue;seen.add(e.id);if(e.type==='INCIDENT'||e.type==='RETIREMENT'){const c=e.carId!=null?R.cars[e.carId]:null;if(c)W.spawnRecovery?.(c,e.type);}}if(seen.size>240){const keep=new Set(R.events.map(e=>e.id));for(const id of [...seen])if(!keep.has(id))seen.delete(id);}}
  function update(dt){const prev=R.cars.map(c=>c.pitState);baseUpdate(dt);const stops=[];for(let i=0;i<R.cars.length;i++){const c=R.cars[i];if(c.retired)continue;if(prev[i]!=='STOP'&&c.pitState==='STOP')onPitEntry(c);updatePitService(c,dt);finishPit(c,prev[i]);updateDamage(c);tyre(c,dt);if(c.pitState==='STOP'){const initial=Math.max(.1,c._pitStopInitial||c.pitTimer||3),p=Math.max(0,Math.min(1,1-(c.pitTimer||0)/initial));stops.push({teamId:c.teamId,carId:c.id,progress:p,service:c.pitService,failure:c._pitFailure});}}W.updatePitService?.(stops);W.updateGridTheatre?.(R.cars,R.sessionPhase,R.race.t,R.race.green);W.updateRecoveries?.(dt);incidents();}
  return new Proxy(R,{get(target,prop){if(prop==='update')return update;if(prop==='pitStrategy')return R.cars.map(c=>({carId:c.id,...strategy(c)}));if(prop==='strategyFor')return c=>strategy(c);return Reflect.get(target,prop,target);}});
}
