import {createUI as createV13UI} from './v13-ui.js';

export function createUI(W,R,D,E,C,A,settings,saveSettings){
  const base=createV13UI(W,R,D,E,C,A,settings,saveSettings),tabs=document.getElementById('v10Tabs'),body=document.getElementById('v10Body');if(!tabs||!body)return base;
  const timing=document.createElement('button');timing.textContent='TIMING';timing.dataset.v15='timing';tabs.insertBefore(timing,tabs.firstChild?.nextSibling||null);
  const cls=document.createElement('button');cls.textContent='CLASS';cls.dataset.v15='class';tabs.insertBefore(cls,tabs.querySelector('[data-v="cam"]'));
  const overlay=document.createElement('div');overlay.id='v15TV';overlay.style.cssText='position:fixed;z-index:59;left:12px;bottom:max(12px,env(safe-area-inset-bottom));padding:7px 10px;border-radius:8px;background:#07121bdf;border:1px solid #ffffff2b;font:800 11px -apple-system,sans-serif;color:#fff;opacity:0;transition:opacity .18s;pointer-events:none;max-width:72vw';document.body.appendChild(overlay);
  let mode='',acc=0,lastEventId=null,showUntil=0;
  function timingHTML(){const st=R.getStandings();let h=`<div class="section"><b>LIVE TIMING · ${R.raceClass||'MIXED'}</b><br><span class="muted">CLASS / GAP / TYRE / PIT / PEN</span></div>`;const lead=st[0];for(const c of st){const gap=c===lead?'LEAD':`+${Math.max(0,((lead._v8Progress??0)-(c._v8Progress??0))/Math.max(1,lead.v)).toFixed(1)}`;h+=`<div class="row tap" data-v15car="${c.id}"><b>${c.position}</b><span>${c.name}<br><span style="color:${c.classColor||'#fff'}">${c.type.toUpperCase()} P${c.classPosition||1}</span><br><span class="muted">ENG ${Math.round(c.engineTemp||0)}° · ${c.tyreCondition||'NORMAL'} · ${c.activeDriver||c.name}</span></span><span>${gap}</span><span>${c.pitState!=='NONE'?'PIT':c.penaltySeconds?`+${c.penaltySeconds}s`:c.compound[0]+Math.round(c.wear*100)}</span></div>`;}body.innerHTML=h;}
  function classHTML(){const cur=(settings.raceClass||'MIXED').toUpperCase(),opts=['MIXED','FORMULA','GT','PROTO','HYPER','TOURING','SUPERCAR','LMH'];body.innerHTML=`<div class="section"><b>VEHICLE CLASS</b><br><span class="muted">次回起動時の20台すべてのカテゴリーを選択</span></div><div class="modegrid">${opts.map(x=>`<button data-class="${x}" class="${x===cur?'on':''}">${x}</button>`).join('')}</div>`;}
  tabs.addEventListener('click',e=>{const b=e.target.closest('[data-v15]');if(!b)return;e.preventDefault();e.stopPropagation();mode=b.dataset.v15;tabs.querySelectorAll('button').forEach(x=>x.classList.toggle('on',x===b));mode==='timing'?timingHTML():classHTML();},{capture:true});
  body.addEventListener('click',e=>{const car=e.target.closest('[data-v15car]');if(car){C.setFocus(Number(car.dataset.v15car));A?.setFocus?.(Number(car.dataset.v15car));return;}const b=e.target.closest('[data-class]');if(b){settings.raceClass=b.dataset.class;saveSettings(settings);location.reload();}});
  function broadcast(){const ev=[...R.events].reverse().find(e=>['GRID_INTRO','POLE_POSITION','FINAL_LAP','FASTEST_LAP','LEAD_CHANGE','SC_IN_THIS_LAP','VSC','RESTART','DRIVER_SWAP','PENALTY','FINISH'].includes(e.type));if(ev&&ev.id!==lastEventId){lastEventId=ev.id;const c=ev.carId!=null?R.cars[ev.carId]:null;let text=ev.type.replaceAll('_',' ');if(c)text+=` · ${c.name}`;if(ev.type==='FASTEST_LAP'&&ev.data?.lapTime)text+=` ${ev.data.lapTime.toFixed(3)}`;overlay.textContent=text;showUntil=performance.now()+2600;}overlay.style.opacity=performance.now()<showUntil?'1':'0';}
  const oldUpdate=base.update;return new Proxy(base,{get(target,prop){if(prop==='update')return(dt,id)=>{oldUpdate(dt,id);acc+=dt;if(acc>.25){acc=0;if(mode==='timing'&&timing.classList.contains('on'))timingHTML();else if(mode==='class'&&cls.classList.contains('on'))classHTML();broadcast();}};return Reflect.get(target,prop,target);}});
}
