export function createAudio(R){
  let ctx=null,master=null,engine1=null,engine2=null,squeal=null,noiseGain=null,radioNoiseGain=null,enabled=false,focus=0,lastGear=0,lastRadioId=null,speaking=false,speechUnlocked=false;
  const queue=[];
  const synth=()=>window.speechSynthesis;
  function init(){if(ctx)return;ctx=new (window.AudioContext||window.webkitAudioContext)();master=ctx.createGain();master.gain.value=.22;master.connect(ctx.destination);engine1=ctx.createOscillator();engine1.type='sawtooth';const g1=ctx.createGain();g1.gain.value=.095;engine1.connect(g1).connect(master);engine1.start();engine2=ctx.createOscillator();engine2.type='triangle';const g2=ctx.createGain();g2.gain.value=.065;engine2.connect(g2).connect(master);engine2.start();squeal=ctx.createOscillator();squeal.type='square';const sq=ctx.createGain();sq.gain.value=0;squeal.connect(sq).connect(master);squeal._gain=sq;squeal.start();const len=ctx.sampleRate*2,b=ctx.createBuffer(1,len,ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<len;i++)d[i]=(Math.random()*2-1)*.38;const wind=ctx.createBufferSource();wind.buffer=b;wind.loop=true;const low=ctx.createBiquadFilter();low.type='lowpass';low.frequency.value=900;noiseGain=ctx.createGain();noiseGain.gain.value=.02;wind.connect(low).connect(noiseGain).connect(master);wind.start();const radio=ctx.createBufferSource();radio.buffer=b;radio.loop=true;const hp=ctx.createBiquadFilter(),lp=ctx.createBiquadFilter();hp.type='highpass';hp.frequency.value=430;lp.type='lowpass';lp.frequency.value=3100;radioNoiseGain=ctx.createGain();radioNoiseGain.gain.value=0;radio.connect(hp).connect(lp).connect(radioNoiseGain).connect(master);radio.start();}
  function setAudioEnabled(on){enabled=!!on;init();if(enabled){ctx.resume?.();master.gain.setTargetAtTime(.22,ctx.currentTime,.04);}else{master.gain.setTargetAtTime(0,ctx.currentTime,.04);synth()?.cancel?.();speaking=false;queue.length=0;}}
  function setFocus(id){focus=Number(id)||0;}function tone(freq=0,dur=.06,vol=.035){if(!ctx||!enabled)return;const o=ctx.createOscillator(),g=ctx.createGain();o.type='square';o.frequency.value=freq;g.gain.setValueAtTime(vol,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+dur);o.connect(g).connect(master);o.start();o.stop(ctx.currentTime+dur+.01);}function txBeep(open=true){tone(open?1120:760,open?.055:.075,open?.045:.035);setTimeout(()=>tone(open?880:610,.045,.024),55);}
  function radioText(msg){let t=String(msg.text||'').replaceAll('·',',').replace(/\bDRS\b/g,'D R S').replace(/\bVSC\b/g,'virtual safety car').replace(/\bSC\b/g,'safety car').replace(/\bP(\d+)\b/g,'position $1').replace(/\bBOX\b/g,'box');if(msg.kind==='CONTROL'&&!/^race control/i.test(t))t=`Race control. ${t}`;return t;}
  function chooseVoice(){const vs=synth()?.getVoices?.()||[];return vs.find(v=>/^en-GB/i.test(v.lang)&&/daniel|oliver|arthur|male/i.test(v.name))||vs.find(v=>/^en-GB/i.test(v.lang))||vs.find(v=>/^en-US/i.test(v.lang))||vs[0]||null;}
  function makeUtterance(msg){const u=new SpeechSynthesisUtterance(radioText(msg)),v=chooseVoice();if(v)u.voice=v;u.lang=v?.lang||'en-GB';u.rate=1.08;u.pitch=.80;u.volume=.88;return u;}
  function radioNoise(on){if(!radioNoiseGain||!ctx)return;radioNoiseGain.gain.setTargetAtTime(on?.050:.0025,ctx.currentTime,on?.012:.055);}
  function speakImmediate(msg,{cancel=false}={}){const s=synth();if(!s||!enabled)return false;if(cancel)s.cancel();const u=makeUtterance(msg);speaking=true;txBeep(true);radioNoise(true);u.onstart=()=>{speechUnlocked=true;radioNoise(true);};u.onend=u.onerror=()=>{txBeep(false);radioNoise(false);speaking=false;setTimeout(speakNext,110);};s.speak(u);return true;}
  function unlockSpeechFromGesture(){if(!synth())return false;speechUnlocked=true;return speakImmediate({text:'Radio check. Comms are good.',kind:'ENGINEER'},{cancel:true});}
  function speakNext(){if(!enabled||speaking||!queue.length||!synth())return;const msg=queue.shift();speakImmediate(msg);}
  function testRadio(){if(!enabled)setAudioEnabled(true);return unlockSpeechFromGesture();}
  function toggle(){if(enabled){setAudioEnabled(false);return false;}setAudioEnabled(true);unlockSpeechFromGesture();return true;}
  function ingestRadio(){const r=R.radio||[];if(!r.length)return;const latest=r[r.length-1];if(!latest||latest.id===lastRadioId)return;lastRadioId=latest.id;const relevant=latest.carId==null||Number(latest.carId)===focus;if(relevant){queue.push(latest);while(queue.length>3)queue.shift();speakNext();}}
  function update(){if(!ctx||!enabled)return;const c=R.cars[focus]||R.getStandings()[0];if(c){const kmh=c.v*3.6,gear=Math.max(1,Math.min(8,Math.floor(kmh/38)+1)),rpm=2600+((kmh%38)*155)+gear*290,base=52+rpm*.022;engine1.frequency.setTargetAtTime(base,ctx.currentTime,.03);engine2.frequency.setTargetAtTime(base*.5,ctx.currentTime,.04);const slip=Math.min(1,(c.brakeVisual||0)*.75+(c.flatSpot?.25:0)+(c.hydroplaning?.18:0));squeal.frequency.setTargetAtTime(610+kmh*2.1,ctx.currentTime,.04);squeal._gain.gain.setTargetAtTime(slip*.024,ctx.currentTime,.04);noiseGain.gain.setTargetAtTime(.008+Math.min(.05,kmh/6500),ctx.currentTime,.08);if(gear!==lastGear&&lastGear>0)tone(125,.055,.035);lastGear=gear;}ingestRadio();}
  return{toggle,testRadio,update,setFocus,get enabled(){return enabled},get speaking(){return speaking},get speechUnlocked(){return speechUnlocked},get speechSupported(){return !!window.speechSynthesis}};
}
