import {createUI as createV17UI} from './v17-ui.js';

export function createUI(W,R,D,E,C,A,settings,saveSettings){
  const base=createV17UI(W,R,D,E,C,A,settings,saveSettings);let telemetryMode=false,acc=0;
  function install(){const tabs=document.getElementById('v16Tabs'),body=document.getElementById('v16Body');if(!tabs||!body||document.getElementById('v18TelemetryTab'))return;const b=document.createElement('button');b.id='v18TelemetryTab';b.textContent='TELEM';b.dataset.v18='telemetry';const cam=tabs.querySelector('[data-tab="cam"]');tabs.insertBefore(b,cam||null);b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();telemetryMode=true;tabs.querySelectorAll('button').forEach(x=>x.classList.toggle('on',x===b));renderTelemetry();},{capture:true});tabs.addEventListener('click',e=>{if(e.target.closest('#v18TelemetryTab'))return;telemetryMode=false;},{capture:true});}
  function graph(canvas,data,series){if(!canvas||data.length<2)return;const dpr=Math.min(devicePixelRatio||1,2),w=Math.max(260,canvas.clientWidth||320),h=118;canvas.width=w*dpr;canvas.height=h*dpr;const g=canvas.getContext('2d');g.scale(dpr,dpr);g.clearRect(0,0,w,h);g.strokeStyle='rgba(255,255,255,.12)';g.lineWidth=1;for(let i=1;i<4;i++){g.beginPath();g.moveTo(0,h*i/4);g.lineTo(w,h*i/4);g.stroke();}for(const s of series){let min=s.min,max=s.max;if(min==null||max==null){const vals=data.map(x=>Number(x[s.key])||0);min=Math.min(...vals);max=Math.max(...vals);if(Math.abs(max-min)<.001){max=min+1;}}g.strokeStyle=s.color;g.lineWidth=1.7;g.beginPath();data.forEach((x,i)=>{const px=i/(data.length-1)*w,py=h-(clamp(((Number(x[s.key])||0)-min)/(max-min),0,1)*h);if(i===0)g.moveTo(px,py);else g.lineTo(px,py);});g.stroke();} }
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  function renderTelemetry(){if(!telemetryMode)return;const body=document.getElementById('v16Body');if(!body)return;const id=Number(C.focus??0),c=R.cars[id]||R.getStandings()[0],data=R.telemetryFor?.(c?.id)||[],p=c?.driverProfile||{};if(!c){body.innerHTML='<div class="muted">No telemetry.</div>';return;}const last=data[data.length-1]||{};body.innerHTML=`<div class="v16section"><b>TELEMETRY · ${c.name}</b><br><span class="muted">${c.type.toUpperCase()} · ${c.driverStyle||'DRIVER'} · last ${(data.length/10).toFixed(0)}s</span></div><div class="v16section"><span class="tag">${Math.round(last.speed||c.v*3.6)} km/h</span><span class="tag">G${last.gear||1}</span><span class="tag good">THR ${Math.round((last.throttle||0)*100)}%</span><span class="tag bad">BRK ${Math.round((last.brake||0)*100)}%</span><span class="tag">STEER ${Math.round((last.steer||0)*100)}</span>${last.drs?'<span class="tag good">DRS</span>':''}${c.spinState!=='NONE'?`<span class="tag warn">${c.spinState}</span>`:''}</div><div class="v16section"><b>SPEED / THROTTLE / BRAKE</b><canvas id="v18Graph1" style="width:100%;height:118px;background:#081017;border-radius:8px;margin-top:5px"></canvas><div class="muted">Speed white · Throttle green · Brake red</div></div><div class="v16section"><b>G / TEMPERATURE</b><canvas id="v18Graph2" style="width:100%;height:118px;background:#081017;border-radius:8px;margin-top:5px"></canvas><div class="muted">Lat-G cyan · Long-G yellow · Tyre magenta · Engine orange</div></div><div class="v16section"><b>DRIVER PROFILE · ${c.driverStyle}</b><br><span class="tag">QUALI ${Math.round((p.quali||1)*100)}</span><span class="tag">PACE ${Math.round((p.pace||1)*100)}</span><span class="tag">CONS ${Math.round((p.consistency||1)*100)}</span><span class="tag">TYRE ${Math.round((p.tyre||1)*100)}</span><span class="tag">WET ${Math.round((p.wet||1)*100)}</span><span class="tag">OVTK ${Math.round((p.overtake||1)*100)}</span><span class="tag">DEF ${Math.round((p.defense||1)*100)}</span><span class="tag">REC ${Math.round((p.recovery||1)*100)}</span></div>`;graph(body.querySelector('#v18Graph1'),data.slice(-180),[{key:'speed',color:'#ffffff',min:0,max:360},{key:'throttle',color:'#5dff8a',min:0,max:1},{key:'brake',color:'#ff6666',min:0,max:1}]);graph(body.querySelector('#v18Graph2'),data.slice(-180),[{key:'gLat',color:'#55dfff',min:-3.5,max:3.5},{key:'gLong',color:'#ffd95a',min:-3.5,max:3.5},{key:'tyre',color:'#ff75dc',min:40,max:130},{key:'engine',color:'#ff9b54',min:70,max:130}]);}
  const observer=new MutationObserver(()=>install());observer.observe(document.body,{childList:true,subtree:true});install();const oldUpdate=base.update;return new Proxy(base,{get(target,prop){if(prop==='update')return(dt,id)=>{oldUpdate(dt,id);install();acc+=dt;if(telemetryMode&&acc>.20){acc=0;renderTelemetry();}};return Reflect.get(target,prop,target);}});
}
