export function createAudio(R){
 let ctx=null,master=null,engine1=null,engine2=null,squeal=null,noiseGain=null,radioNoiseGain=null,enabled=false,focus=0,lastGear=0,lastRadioId=null,speaking=false,speechUnlocked=false,stage='NONE',stageCar=null;const queue=[];const synth=()=>window.speechSynthesis;
 function init(){if(ctx)return;ctx=new (window.AudioContext||window.webkitAudioContext)();master=ctx.createGain();master.gain.value=.22;master.connect(ctx.destination);engine1=ctx.createOscillator();engine1.type='sawtooth';const g1=ctx.createGain();g1.gain.value=.095;engine1.connect(g1).connect(master);engine1.start();engine2=ctx.createOscillator();engine2.type='triangle';const g2=ctx.createGain();g2.gain.value=.065;engine2.connect(g2).connect(master);engine2.start();squeal=ctx.createOscillator();squeal.type='square';const sq=ctx.createGain();sq.gain.value=0;squeal.connect(sq).connect(master);squeal._gain=sq;squeal.start();const len=ctx.sampleRate*2,b=ctx.createBuffer(1,len,ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<len;i++)d[i]=(Math.random()*2-1)*.38;const wind=ctx.createBufferSource();wind.buffer=b;wind.loop=true;const low=ctx.createBiquadFilter();low.type='lowpass';low.frequency.value=900;noiseGain=ctx.createGain();noiseGain.gain.value=.02;wind.connect(low).connect(noiseGain).connect(master);wind.start();const radio=ctx.createBufferSource();radio.buffer=b;radio.loop=true;const hp=ctx.createBiquadFilter(),lp=ctx.createBiquadFilter();hp.type='highpass';hp.frequency.value=430;lp.type='lowpass';lp.frequency.value=3100;radioNoiseGain=ctx.createGain();radioNoiseGain.gain.value=0;radio.connect(hp).connect(lp).connect(radioNoiseGain).connect(master);radio.start();}
 function markNow(){const r=R.radio||[];lastRadioId=r.length?r[r.length-1].id:null;queue.length=0;stage='NONE';stageCar=null;}
 function setEnabled(on){enabled=!!on;init();if(enabled){ctx.resume?.();master.gain.setTargetAtTime(.22,ctx.currentTime,.04);markNow();}else{master.gain.setTargetAtTime(0,ctx.currentTime,.04);synth()?.cancel?.();speaking=false;markNow();}}
 function setFocus(id){const n=Number(id)||0;if(n!==focus){focus=n;markNow();}else focus=n;}
 function tone(freq,dur=.06,vol=.035){if(!ctx||!enabled)return;const o=ctx.createOscillator(),g=ctx.createGain();o.type='square';o.frequency.value=freq;g.gain.setValueAtTime(vol,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+dur);o.connect(g).connect(master);o.start();o.stop(ctx.currentTime+dur+.01);}function txBeep(open=true){tone(open?1120:760,open?.055:.075,open?.045:.035);setTimeout(()=>tone(open?880:610,.045,.024),55);}
 function radioText(msg){return String(msg.text||'').replaceAll('·',',').replace(/\bDRS\b/g,'D R S').replace(/\bVSC\b/g,'virtual safety car').replace(/\bSC\b/g,'safety car').replace(/\bP(\d+)\b/g,'position $1').replace(/\bBOX\b/g,'box');}
 function voices(){return synth()?.getVoices?.()||[];}function engineerVoice(){const vs=voices();return vs.find(v=>/^en-GB/i.test(v.lang)&&/daniel|oliver|arthur|male/i.test(v.name))||vs.find(v=>/^en-GB/i.test(v.lang))||vs.find(v=>/^en-US/i.test(v.lang))||vs[0]||null;}function driverVoice(){const vs=voices(),eng=engineerVoice();return vs.find(v=>v!==eng&&/^en-(US|AU|IE|GB)/i.test(v.lang))||eng||vs[0]||null;}
 function makeUtterance(msg){const driver=msg.kind==='DRIVER',v=driver?driverVoice():engineerVoice(),u=new SpeechSynthesisUtterance(radioText(msg));if(v)u.voice=v;u.lang=v?.lang||'en-GB';u.rate=driver?1.00:1.10;u.pitch=driver?.98:.80;u.volume=driver?.92:.88;return u;}
 function radioNoise(on){if(!radioNoiseGain||!ctx)return;radioNoiseGain.gain.setTargetAtTime(on?.050:.0025,ctx.currentTime,on?.012:.055);}
 function speakImmediate(msg,{cancel=false}={}){const s=synth();if(!s||!enabled)return false;if(cancel)s.cancel();const u=makeUtterance(msg);speaking=true;txBeep(true);radioNoise(true);u.onstart=()=>{speechUnlocked=true;};u.onend=u.onerror=()=>{txBeep(false);radioNoise(false);speaking=false;setTimeout(speakNext,105);};s.speak(u);return true;}
 function unlock(){if(!synth())return false;speechUnlocked=true;return speakImmediate({text:'Radio check. Engineer to driver. Comms are good.',kind:'ENGINEER_AI'},{cancel:true});}
 function speakNext(){if(!enabled||speaking||!queue.length||!synth())return;speakImmediate(queue.shift());}
 function testRadio(){if(!enabled)setEnabled(true);return unlock();}function toggle(){if(enabled){setEnabled(false);return false;}setEnabled(true);unlock();return true;}
 const engineerKinds=new Set(['ENGINEER_AI','ENGINEER','PIT','STRATEGY','TYRE','URGENT','FAULT']);
 function accept(msg){if(!msg||msg.carId==null||msg.kind==='CONTROL'||Number(msg.carId)!==focus)return false;if(engineerKinds.has(msg.kind)){stage='ENGINEER';stageCar=focus;return true;}if(msg.kind==='DRIVER'&&stage==='ENGINEER'&&stageCar===focus){stage='DRIVER';return true;}if(msg.kind==='ENGINEER_REPLY'&&stage==='DRIVER'&&stageCar===focus){stage='ENGINEER';return true;}return false;}
 function ingestRadio(){const r=R.radio||[];if(!r.length)return;const latest=r[r.length-1];if(!latest||latest.id===lastRadioId)return;lastRadioId=latest.id;if(accept(latest)){queue.push(latest);while(queue.length>5)queue.shift();speakNext();}}
 function update(){if(!ctx||!enabled)return;const c=R.cars[focus]||R.getStandings()[0];if(c){const kmh=c.v*3.6,gear=Math.max(1,Math.min(8,Math.floor(kmh/38)+1)),rpm=2600+((kmh%38)*155)+gear*290,base=52+rpm*.022;engine1.frequency.setTargetAtTime(base,ctx.currentTime,.03);engine2.frequency.setTargetAtTime(base*.5,ctx.currentTime,.04);const slip=Math.min(1,(c.brakeVisual||0)*.75+(c.flatSpot?.25:0)+(c.hydroplaning?.18:0)+(c.spinState==='SLIDE'?.35:0));squeal.frequency.setTargetAtTime(610+kmh*2.1,ctx.currentTime,.04);squeal._gain.gain.setTargetAtTime(slip*.024,ctx.currentTime,.04);noiseGain.gain.setTargetAtTime(.008+Math.min(.05,kmh/6500),ctx.currentTime,.08);if(gear!==lastGear&&lastGear>0)tone(125,.055,.035);lastGear=gear;}ingestRadio();}
 return{toggle,testRadio,update,setFocus,get enabled(){return enabled},get speaking(){return speaking},get speechUnlocked(){return speechUnlocked},get speechSupported(){return !!window.speechSynthesis}};
}
