export function createCamera(W,R,D,camEl){
  const T=W.THREE,{total,clamp}=W,anchorFracs=[.002,.055,.12,.20,.31,.43,.55,.68,.79,.90,.965];
  const anchors=anchorFracs.map(f=>{const q=W.sample(total*f),p=q.p.clone().addScaledVector(q.side,32);p.y+=11.5;return{s:total*f,p};});
  const camP=new T.Vector3(),look=new T.Vector3(),desiredP=new T.Vector3(),desiredLook=new T.Vector3(),off=new T.Vector3(),right=new T.Vector3(),up=new T.Vector3(0,1,0),localP=new T.Vector3(),localT=new T.Vector3(),photoTarget=new T.Vector3(),photoPos=new T.Vector3();
  let mode='AUTO',focus=0,tv=-1,lastCut=-999,ready=false,yaw=0,pitch=0,zoom=1,drag=false,lastX=0,lastY=0,lastTap=0,pinch=0,photoInit=false,pitLock=false,pitId=-1,pitPX=0,pitPY=0,pitPZ=0,pitTX=0,pitTY=0,pitTZ=0,currentFov=50;
  const distTrack=(a,b)=>{const d=Math.abs(a-b);return Math.min(d,total-d);};
  function activeFocus(){return mode==='AUTO'?Number(D.focus||0):focus;}
  function worldLocal(c,a,out){out.set(a[0],a[1],a[2]);c.mesh.localToWorld(out);return out;}
  function setFov(v,dt,rate=5.8){const f=1-Math.exp(-rate*dt),next=currentFov+(v-currentFov)*f;if(Math.abs(next-currentFov)>.02){currentFov=next;W.camera.fov=next;W.camera.updateProjectionMatrix();}}
  function onboard(c,which){const A=c.mesh.userData.cameraAnchors||{},cock=A.cockpit||[0,1.2,.4],nose=A.nose||[0,.7,3],bumper=A.bumper||[0,.45,3.5],rear=A.rear||[0,1,-3],wheel=A.wheel||[-1.2,.55,1.7];let pA=cock,tA=[0,cock[1],11];if(which==='NOSE'){pA=nose;tA=[0,nose[1]+.2,15];}else if(which==='BUMPER'){pA=bumper;tA=[0,bumper[1]+.2,15];}else if(which==='REAR'){pA=rear;tA=[0,rear[1],-15];}else if(which==='WHEEL'){pA=wheel;tA=[0,wheel[1]+.1,12];}worldLocal(c,pA,desiredP);worldLocal(c,tA,desiredLook);return{roadY:c.mesh.position.y-.2,rate:13,onboard:true};}
  function scoreAnchor(i,c){const a=anchors[i],dx=a.p.x-c.mesh.position.x,dy=a.p.y-c.mesh.position.y,dz=a.p.z-c.mesh.position.z,dist=Math.hypot(dx,dy,dz),inv=1/Math.max(.001,dist),yawC=c.mesh.rotation.y||0,fx=Math.sin(yawC),fz=Math.cos(yawC),dot=Math.min(1,Math.abs(fx*dx*inv+fz*dz*inv)),angle=Math.acos(dot)*180/Math.PI,td=distTrack(a.s,c.s),distScore=clamp(1-Math.abs(dist-105)/145,0,1),angleScore=clamp(1-Math.abs(angle-70)/70,0,1),trackScore=clamp(1-td/300,0,1),continuity=i===tv?.42:0;return{score:distScore*.44+angleScore*.32+trackScore*.24+continuity,dist,angle};}
  function chooseTV(c,now){let bestI=0,bestS=-1,bestDist=0,bestAngle=0;for(let i=0;i<anchors.length;i++){const x=scoreAnchor(i,c);if(x.score>bestS){bestS=x.score;bestI=i;bestDist=x.dist;bestAngle=x.angle;}}let current=tv>=0?scoreAnchor(tv,c):null;const invalid=!current||current.dist>245||current.dist<28||current.angle<18,better=current&&bestS>current.score+.28;if(tv<0||invalid||(now-lastCut>6500&&better)){tv=bestI;lastCut=now;ready=false;current={dist:bestDist,angle:bestAngle};}return current||scoreAnchor(tv,c);}
  function tvShot(c,dt,now){const meta=chooseTV(c,now),a=anchors[tv],yawC=c.mesh.rotation.y||0,lead=Math.min(22,(c.v||0)*.16);desiredP.copy(a.p);desiredLook.copy(c.mesh.position);desiredLook.x+=Math.sin(yawC)*lead;desiredLook.z+=Math.cos(yawC)*lead;desiredLook.y+=1.15;const travel=camP.distanceTo(desiredP);if(!ready||travel>220){camP.copy(desiredP);if(!ready)look.copy(desiredLook);ready=true;}else{const fp=1-Math.exp(-8*dt);camP.lerp(desiredP,fp);}look.lerp(desiredLook,1-Math.exp(-4.2*dt));setFov(clamp(52-(meta.dist-50)*.115,32,52),dt);camEl.textContent=`AUTO · TV · ${Math.round(meta.dist)}m · ${Math.round(meta.angle)}°`;return{roadY:c.mesh.position.y-.3,onboard:false};}
  function pitShot(c,dt){if(!pitLock||pitId!==c.id){const q=W.pitPose?.(c.s,c.teamId,'STOP');if(q){desiredP.copy(q.p).addScaledVector(q.side,-6.6);desiredP.y+=2.55;desiredLook.copy(q.p);desiredLook.y+=.72;}else{desiredP.copy(c.mesh.position);desiredP.x+=6;desiredP.y+=2.5;desiredP.z-=2;desiredLook.copy(c.mesh.position);desiredLook.y+=.7;}pitPX=desiredP.x;pitPY=desiredP.y;pitPZ=desiredP.z;pitTX=desiredLook.x;pitTY=desiredLook.y;pitTZ=desiredLook.z;pitId=c.id;pitLock=true;camP.copy(desiredP);look.copy(desiredLook);ready=true;}desiredP.set(pitPX,pitPY,pitPZ);if(c.pitState==='ENTRY'||c.pitState==='EXIT'){desiredLook.copy(c.mesh.position);desiredLook.y+=.65;}else desiredLook.set(pitTX,pitTY,pitTZ);camP.copy(desiredP);look.lerp(desiredLook,1-Math.exp(-4*dt));setFov(42,dt);camEl.textContent=`AUTO · PIT STATIC · ${c.name}`;return{roadY:c.mesh.position.y-.3,onboard:false};}
  function movingShot(c,dt,kind){const y=c.mesh.rotation.y||0,fx=Math.sin(y),fz=Math.cos(y),rx=Math.cos(y),rz=-Math.sin(y);if(kind==='HELI'){desiredP.set(c.mesh.position.x-fx*18,c.mesh.position.y+62,c.mesh.position.z-fz*18);desiredLook.set(c.mesh.position.x+fx*32,c.mesh.position.y+1,c.mesh.position.z+fz*32);setFov(46,dt);}else{desiredP.set(c.mesh.position.x-fx*24+rx*5,c.mesh.position.y+7.5,c.mesh.position.z-fz*24+rz*5);desiredLook.set(c.mesh.position.x+fx*34,c.mesh.position.y+1.1,c.mesh.position.z+fz*34);setFov(48,dt);}const travel=camP.distanceTo(desiredP);if(!ready||travel>220){camP.copy(desiredP);look.copy(desiredLook);ready=true;}else{camP.lerp(desiredP,1-Math.exp(-(kind==='HELI'?1.8:3.2)*dt));look.lerp(desiredLook,1-Math.exp(-4*dt));}camEl.textContent=`AUTO · ${kind} · ${D.reason||'EVENT'}`;return{roadY:c.mesh.position.y-.3,onboard:false};}
  function formationShot(c,dt){const q=W.sample(c.s,c.lane),ahead=W.sample(c.s+52,c.lane);desiredP.copy(q.p).addScaledVector(q.t,-24).addScaledVector(q.side,5);desiredP.y+=7;desiredLook.copy(ahead.p);desiredLook.y+=1.4;camP.lerp(desiredP,1-Math.exp(-4*dt));look.lerp(desiredLook,1-Math.exp(-4*dt));return{roadY:q.p.y,onboard:false};}
  function startShot(dt){const a=W.sample(-12),b=W.sample(85);desiredP.copy(a.p).addScaledVector(a.side,48);desiredP.y+=16;desiredLook.copy(b.p);desiredLook.y+=2;camP.lerp(desiredP,1-Math.exp(-5*dt));look.lerp(desiredLook,1-Math.exp(-5*dt));return{roadY:a.p.y,onboard:false};}
  function manualOrAuto(dt,now){const idx=activeFocus(),c=R.cars[idx]||R.cars[0],active=mode==='AUTO'?String(D.shot||'TV'):mode;if(!c)return{idx:0,roadY:0,onboard:false};if(mode==='PHOTO'){if(!photoInit){photoTarget.copy(c.mesh.position);photoTarget.y+=1.1;photoPos.copy(W.camera.position);if(photoPos.distanceTo(photoTarget)<5){photoPos.copy(photoTarget);photoPos.y+=8;photoPos.z-=25;}photoInit=true;}desiredP.copy(photoPos);desiredLook.copy(photoTarget);camP.lerp(desiredP,1-Math.exp(-8*dt));look.lerp(desiredLook,1-Math.exp(-8*dt));return{idx,roadY:Math.min(photoTarget.y-1,0),onboard:false};}if(['COCKPIT','NOSE','REAR','WHEEL','BUMPER'].includes(active)){const x=onboard(c,active);camP.lerp(desiredP,1-Math.exp(-13*dt));look.lerp(desiredLook,1-Math.exp(-13*dt));return{idx,...x};}if(R.sessionPhase==='FORMATION')return{idx,...formationShot(c,dt)};if(R.race.t<(R.race.green||0)+6&&R.sessionPhase!=='QUALIFYING')return{idx,...startShot(dt)};if(mode==='AUTO'&&(active==='PIT'||D.pitEventFocus===c.id))return{idx,...pitShot(c,dt)};pitLock=false;pitId=-1;if(active==='HELI'||active==='CHASE')return{idx,...movingShot(c,dt,active)};return{idx,...tvShot(c,dt,now)};}
  function update(dt,now=performance.now()){const d=manualOrAuto(dt,now);off.copy(camP).sub(look).multiplyScalar(zoom);off.applyAxisAngle(up,yaw);right.crossVectors(up,off);if(right.lengthSq()>.001){right.normalize();off.applyAxisAngle(right,pitch);}W.camera.position.copy(look).add(off);const floor=d.roadY+(W.cameraMinClearance??.9);if(!d.onboard&&W.camera.position.y<floor)W.camera.position.y=floor;W.camera.lookAt(look);const leader=R.getStandings()[0];if(leader&&W.sun){W.sun.target.position.copy(leader.mesh.position);W.sun.position.set(leader.mesh.position.x+260,leader.mesh.position.y+420,leader.mesh.position.z+180);}if(mode!=='AUTO')camEl.textContent=mode+' · 360°';return d.idx;}
  function setMode(m){mode=m;ready=false;photoInit=m==='PHOTO'?false:photoInit;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));}
  function setFocus(n){focus=(Number(n)+R.cars.length)%R.cars.length;D.userFocus(focus);ready=false;}
  function move(x,y){if(!drag)return;const dx=x-lastX,dy=y-lastY;lastX=x;lastY=y;yaw-=dx*.0065;pitch=clamp(pitch-dy*.0048,-1.20,1.20);}
  function panPhoto(dx,dy,dz){if(mode!=='PHOTO')setMode('PHOTO');photoTarget.x+=dx;photoTarget.y+=dy;photoTarget.z+=dz;photoPos.x+=dx;photoPos.y+=dy;photoPos.z+=dz;ready=false;}
  const el=W.renderer.domElement;el.style.touchAction='none';el.addEventListener('touchstart',e=>{e.preventDefault();if(e.touches.length===2){drag=false;pinch=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);return;}if(e.touches.length!==1)return;const t=e.touches[0],n=performance.now();if(n-lastTap<320){yaw=0;pitch=0;zoom=1;}lastTap=n;drag=true;lastX=t.clientX;lastY=t.clientY;},{passive:false});el.addEventListener('touchmove',e=>{e.preventDefault();if(e.touches.length===2){const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);if(pinch>0)zoom=clamp(zoom*pinch/d,.28,4);pinch=d;return;}if(e.touches.length===1)move(e.touches[0].clientX,e.touches[0].clientY);},{passive:false});el.addEventListener('touchend',e=>{if(e.touches.length<2)pinch=0;if(e.touches.length===0)drag=false;},{passive:true});el.addEventListener('wheel',e=>{e.preventDefault();zoom=clamp(zoom*Math.exp(e.deltaY*.001),.28,4);},{passive:false});el.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')return;drag=true;lastX=e.clientX;lastY=e.clientY;el.setPointerCapture?.(e.pointerId);});el.addEventListener('pointermove',e=>{if(e.pointerType!=='touch')move(e.clientX,e.clientY);});el.addEventListener('pointerup',()=>drag=false);document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));document.getElementById('next')?.addEventListener('click',()=>setFocus(focus+1));document.getElementById('prev')?.addEventListener('click',()=>setFocus(focus-1));
  return{update,setMode,setFocus,panPhoto,zoomIn:()=>zoom=clamp(zoom*.78,.28,4),zoomOut:()=>zoom=clamp(zoom*1.28,.28,4),reset:()=>{yaw=0;pitch=0;zoom=1;ready=false;},setFov:v=>{currentFov=clamp(Number(v),25,90);W.camera.fov=currentFov;W.camera.updateProjectionMatrix();},setExposure:v=>W.renderer.toneMappingExposure=clamp(Number(v),.45,1.8),get zoom(){return zoom},get yaw(){return yaw},get mode(){return mode},get focus(){return focus},get tvAnchor(){return tv}};
}
