import {createRace as createV31Race} from './v31-race.js';

export function createRace(W,statusEl,settings={}){
  const R=createV31Race(W,statusEl,settings),baseUpdate=R.update,baseStandings=R.getStandings.bind(R),spins=new Map(),contactLatch=new Set(),barrierCooldown=new Map(),history=[];
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));let standingsCache=baseStandings();
  const emit=(type,c,data={})=>{R.events?.push({id:`v38-${Date.now()}-${Math.random()}`,type,t:R.race.t,carId:c?.id??null,data});while(R.events?.length>180)R.events.shift();};
  const radio=(c,text,kind='URGENT')=>{if(!R.radio||!c)return;R.radio.push({id:`v38r-${Date.now()}-${Math.random()}`,t:R.race.t,carId:c.id,name:c.name,text,kind});while(R.radio.length>40)R.radio.shift();};
  const massOf=c=>c.massKg||c.classPerformance?.massKg||({formula:800,hyper:1030,lmh:1030,proto:950,gt:1300,supercar:1450,touring:1320}[c.type]||1100);
  const spinKind=s=>s<.46?'LIGHT':s<.74?'MAJOR':'VIOLENT';
  function beginSpin(c){const severity=clamp(Number(c.spinSeverity)||.5,.2,1),kind=spinKind(severity),dir=Math.sign(c._spinDir||1),s={kind,severity,dir,extra:0,latVel:kind==='LIGHT'?.8+severity:kind==='MAJOR'?2.4+severity*2.2:4.2+severity*3,startedAt:R.race.t,barrierHits:0};spins.set(c.id,s);c.spinClass=kind;c.crashState='NONE';if(kind==='LIGHT')c.spinTimer=Math.min(c.spinTimer||.75,.78);if(kind==='MAJOR')c.spinTimer=Math.max(c.spinTimer||0,1.18);if(kind==='VIOLENT')c.spinTimer=Math.max(c.spinTimer||0,1.65);emit('SPIN_CLASS',c,{kind,severity,entryKmh:Math.round((c.v||0)*3.6)});return s;}
  function damageBand(kmh){if(kmh<15)return{label:'SCRAPE',damage:.018,speed:.90};if(kmh<38)return{label:'LIGHT',damage:.055,speed:.78};if(kmh<72)return{label:'MODERATE',damage:.15,speed:.58};if(kmh<115)return{label:'HEAVY',damage:.32,speed:.34};if(kmh<160)return{label:'SEVERE',damage:.55,speed:.16};return{label:'DESTROYED',damage:.88,speed:0};}
  function retireIfNeeded(c,cause,impactKmh,forced=false){if(c.retired)return true;if(forced||(c.damage||0)>=.90){c.damage=1;c.v=0;c.retired=true;c.fault='CRASH';c.spinState='NONE';c.crashState='DESTROYED';W.spawnDebris?.(c,10);W.spawnRecovery?.(c,'CRASH');emit('RETIREMENT',c,{reason:cause,impactKmh:Math.round(impactKmh)});radio(c,'Big impact. Stop the car. Stop the car.','FAULT');return true;}if((c.damage||0)>=.68){c.fault='SUSPENSION DAMAGE';c.v=Math.min(c.v,18);if(c.pitState==='NONE')c.pitState='ENTRY';c.crashState='HEAVY';}else if((c.damage||0)>=.38){c.fault='CRASH DAMAGE';c.v=Math.min(c.v,32);c.crashState='MODERATE';}return false;}
  function applyDamage(c,amount,cause,impactKmh,forced=false){c.damage=clamp((c.damage||0)+Math.max(0,amount),0,1);W.updateCarDamage?.(c);return retireIfNeeded(c,cause,impactKmh,forced);}
  function updateSpinMotion(c,dt,before){let s=spins.get(c.id);if(c.spinState==='SLIDE'&&before!=='SLIDE'&&!s)s=beginSpin(c);if(!s||c.retired)return;const q=W.sample(c.s,c.lane);if(c.spinState==='SLIDE'){const slip=Math.max(.16,Math.abs(Math.sin(c.slipAngle||0))),speedFactor=clamp((c.v||0)/45,.25,1.35);s.extra+=s.dir*s.latVel*slip*dt*(s.kind==='LIGHT'?.28:speedFactor);s.extra=clamp(s.extra,-6.6,6.6);c.mesh.position.addScaledVector(q.side,s.extra);if(Math.abs((c.lane||0)+s.extra)>4.6){c.offTrack=true;c.v=Math.max(0,c.v-dt*(s.kind==='VIOLENT'?18:11));}}else if(c.spinState==='RECOVER'){s.extra*=Math.exp(-dt*(s.kind==='LIGHT'?3.5:1.25));c.mesh.position.addScaledVector(q.side,s.extra);}else if(c.spinState==='NONE'){s.extra*=Math.exp(-dt*2.2);if(Math.abs(s.extra)>.04)c.mesh.position.addScaledVector(q.side,s.extra);else{spins.delete(c.id);c.offTrack=false;}}}
  function barrierPhysics(c){if(!c?.mesh||c.retired||!W.barrierContact)return;const hit=W.barrierContact(c);if(!hit)return;const last=barrierCooldown.get(c.id)||-99;if(R.race.t-last<.42)return;barrierCooldown.set(c.id,R.race.t);const yaw=c.mesh.rotation.y||0,fx=Math.sin(yaw),fz=Math.cos(yaw),normal=hit.inward,normalMs=Math.abs((fx*normal.x+fz*normal.z)*(c.v||0)),impactKmh=normalMs*3.6,band=damageBand(impactKmh),s=spins.get(c.id),q=W.sample(c.s,c.lane);c.mesh.position.addScaledVector(hit.inward,hit.penetration+.10);if(s){s.extra+=hit.inward.dot(q.side)*(hit.penetration+.18);s.barrierHits++;}c.v*=band.speed;c.laneTarget=clamp((c.laneTarget||0)+hit.inward.dot(q.side)*1.1,-4.2,4.2);c.crashState=band.label;applyDamage(c,band.damage*(1+(s?.severity||0)*.30),'BARRIER',impactKmh,band.label==='DESTROYED');W.spawnDebris?.(c,band.label==='SCRAPE'?1:band.label==='LIGHT'?2:band.label==='MODERATE'?4:band.label==='HEAVY'?7:10);emit('BARRIER_IMPACT',c,{physical:true,impactKmh:Math.round(impactKmh),damageBand:band.label,barrierIndex:hit.collider.index,side:hit.collider.sideSign});if(impactKmh>=38)emit('INCIDENT',c,{physical:true,kind:'BARRIER',impactKmh:Math.round(impactKmh),severity:clamp(impactKmh/170,0,1)});history.push({type:'BARRIER',carId:c.id,t:R.race.t,impactKmh,band:band.label});while(history.length>60)history.shift();}
  function shape(c,out){const yaw=c.mesh?.rotation?.y||0;out.fx=Math.sin(yaw);out.fz=Math.cos(yaw);out.rx=Math.cos(yaw);out.rz=-Math.sin(yaw);out.L=(c.length||c.mesh?.userData?.dims?.length||5.1)*.5;out.W=(c.width||c.mesh?.userData?.dims?.width||2)*.5;out.x=c.mesh.position.x;out.z=c.mesh.position.z;return out;}
  const A={},B={};
  function projectionRadius(S,ax,az){return S.L*Math.abs(S.fx*ax+S.fz*az)+S.W*Math.abs(S.rx*ax+S.rz*az);}
  function obbContact(a,b){shape(a,A);shape(b,B);const dx=B.x-A.x,dz=B.z-A.z,axes=[[A.fx,A.fz],[A.rx,A.rz],[B.fx,B.fz],[B.rx,B.rz]];let min=Infinity,nx=0,nz=0;for(let i=0;i<4;i++){let ax=axes[i][0],az=axes[i][1],len=Math.hypot(ax,az)||1;ax/=len;az/=len;const over=projectionRadius(A,ax,az)+projectionRadius(B,ax,az)-Math.abs(dx*ax+dz*az);if(over<=0)return null;if(over<min){min=over;const sign=(dx*ax+dz*az)<0?-1:1;nx=ax*sign;nz=az*sign;}}return{nx,nz,penetration:min,aFx:A.fx,aFz:A.fz,bFx:B.fx,bFz:B.fz};}
  function pairKey(a,b){return a.id<b.id?`${a.id}-${b.id}`:`${b.id}-${a.id}`;}
  function carCrash(a,b,c){const key=pairKey(a,b);if(contactLatch.has(key))return;contactLatch.add(key);const av=a.retired?0:(a.v||0),bv=b.retired?0:(b.v||0),vax=c.aFx*av,vaz=c.aFz*av,vbx=c.bFx*bv,vbz=c.bFz*bv,rvx=vax-vbx,rvz=vaz-vbz,totalRel=Math.hypot(rvx,rvz)*3.6;let impactKmh=Math.abs(rvx*c.nx+rvz*c.nz)*3.6;const hazardA=a.spinState!=='NONE'||a.v<8||a.retired,hazardB=b.spinState!=='NONE'||b.v<8||b.retired;if(hazardA||hazardB)impactKmh=Math.max(impactKmh,totalRel*.62);const broadside=Math.abs(c.aFx*c.bFz-c.aFz*c.bFx),sideBySide=!hazardA&&!hazardB&&broadside<.35&&impactKmh<18;if(sideBySide){a.v*=.995;b.v*=.995;emit('RUBBING',a,{otherId:b.id,physical:true,impactKmh:Math.round(impactKmh)});return;}const sev=clamp((impactKmh-8)/150,0,1),base=.012+Math.pow(sev,1.35)*.72,ma=massOf(a),mb=massOf(b),sum=ma+mb,da=base*(mb/sum)*2,db=base*(ma/sum)*2;a.v*=clamp(1-sev*.54,.22,.98);b.v*=clamp(1-sev*.54,.22,.98);a.mesh.position.x-=c.nx*c.penetration*.52;a.mesh.position.z-=c.nz*c.penetration*.52;b.mesh.position.x+=c.nx*c.penetration*.52;b.mesh.position.z+=c.nz*c.penetration*.52;applyDamage(a,da,'CAR COLLISION',impactKmh,impactKmh>168&&da>.48);applyDamage(b,db,'CAR COLLISION',impactKmh,impactKmh>168&&db>.48);if(impactKmh>48){if(!a.retired&&a.spinState==='NONE'){a.spinState='SLIDE';a.spinSeverity=Math.max(a.spinSeverity||0,clamp(sev*.85,.35,.92));}if(!b.retired&&b.spinState==='NONE'){b.spinState='SLIDE';b.spinSeverity=Math.max(b.spinSeverity||0,clamp(sev*.85,.35,.92));}}const primary=(vax*c.nx+vaz*c.nz)>(vbx*c.nx+vbz*c.nz)?a:b,other=primary===a?b:a;W.spawnDebris?.(primary,impactKmh>110?8:impactKmh>65?4:2);emit('CONTACT',primary,{otherId:other.id,physical:true,impactKmh:Math.round(impactKmh),severity:sev,damageA:da,damageB:db});if(impactKmh>42)emit('INCIDENT',primary,{otherId:other.id,physical:true,kind:'CAR_CAR',impactKmh:Math.round(impactKmh),severity:sev});history.push({type:'CAR_CAR',a:a.id,b:b.id,t:R.race.t,impactKmh,damageA:da,damageB:db});while(history.length>60)history.shift();}
  function candidates(){const map=R.spatialNeighbours,pairs=[],seen=new Set();if(map?.size){for(const a of R.cars){if(!a.mesh||a.mesh.visible===false)continue;let x=map.get(a.id),b=x?.ahead;for(let depth=0;depth<2&&b;depth++){const k=pairKey(a,b);if(!seen.has(k)){seen.add(k);pairs.push([a,b]);}x=map.get(b.id);b=x?.ahead;}}}else{for(let i=0;i<R.cars.length;i++)for(let j=i+1;j<Math.min(R.cars.length,i+3);j++)pairs.push([R.cars[i],R.cars[j]]);}return pairs;}
  function carContacts(){const still=new Set();for(const [a,b] of candidates()){if(!a?.mesh||!b?.mesh||a.mesh.visible===false||b.mesh.visible===false)continue;const c=obbContact(a,b),key=pairKey(a,b);if(c){still.add(key);carCrash(a,b,c);}}for(const key of contactLatch)if(!still.has(key))contactLatch.delete(key);}
  function update(dt){const before=R.cars.map(c=>c.spinState);baseUpdate(dt);for(let i=0;i<R.cars.length;i++)updateSpinMotion(R.cars[i],dt,before[i]);for(const c of R.cars)barrierPhysics(c);carContacts();standingsCache=baseStandings();}
  return new Proxy(R,{get(target,prop){if(prop==='update')return update;if(prop==='getStandings')return()=>standingsCache;if(prop==='leader')return()=>standingsCache[0]?.id??0;if(prop==='physicalCrashHistory')return history;if(prop==='physicalSpinStates')return[...spins].map(([carId,s])=>({carId,...s}));return Reflect.get(target,prop,target);}});
}
