export function createCamera(W,R,camEl){
 const T=W.THREE,{sample,total,v3,clamp,camera,renderer,sun}=W;let mode='AUTO',auto='TV',focus=0,autoT=0,tv=-1,lastCut=-999,ready=false,yaw=0,pitch=0,drag=false,lastX=0,lastY=0,lastTap=0;const anchors=[.002,.055,.12,.20,.31,.43,.55,.68,.79,.90,.965],camP=v3(),look=v3(),up=v3(0,1,0),off=v3(),right=v3();
 const nearest=fr=>{let k=0,d=9;for(let i=0;i<anchors.length;i++){const q=Math.min(Math.abs(fr-anchors[i]),1-Math.abs(fr-anchors[i]));if(q<d){d=q;k=i;}}return k;};
 function desired(active,now){const idx=R.race.t<R.race.green+9?R.leader():focus,c=R.cars[idx],q=sample(c.s,c.lane),ahead=sample(c.s+52,c.lane);if(R.race.t<R.race.green+6){const a=sample(-12),b=sample(85);return{p:a.p.clone().addScaledVector(a.side,48).add(v3(0,16,0)),target:b.p.clone().add(v3(0,2,0)),k:5,cut:false};}if(active==='CHASE')return{p:q.p.clone().addScaledVector(q.t,-28).addScaledVector(q.side,6).add(v3(0,8,0)),target:ahead.p.clone().add(v3(0,1.5,0)),k:3,cut:false};if(active==='HELI')return{p:q.p.clone().addScaledVector(q.t,-22).add(v3(0,76,0)),target:ahead.p.clone(),k:1.4,cut:false};const k=nearest(c.s/total);let cut=false;if(k!==tv&&now-lastCut>1500){tv=k;lastCut=now;cut=true;}if(tv<0){tv=k;lastCut=now;cut=true;}const a=sample(total*anchors[tv]);return{p:a.p.clone().addScaledVector(a.side,31).add(v3(0,12,0)),target:q.p.clone().add(v3(0,1.4,0)),k:5.5,cut};}
 function update(dt,now){autoT+=dt;if(mode==='AUTO'&&R.race.t>R.race.green+7&&autoT>7){autoT=0;auto=auto==='TV'?'CHASE':auto==='CHASE'?'HELI':'TV';camEl.textContent=`AUTO · ${auto} · SWIPE`;ready=false;}const active=mode==='AUTO'?auto:mode,d=desired(active,now);if(!ready||d.cut){camP.copy(d.p);look.copy(d.target);ready=true;}else{const f=1-Math.exp(-d.k*dt);camP.lerp(d.p,f);look.lerp(d.target,f);}off.copy(camP).sub(look).applyAxisAngle(up,yaw);right.crossVectors(up,off).normalize();if(right.lengthSq()>.001)off.applyAxisAngle(right,pitch);camera.position.copy(look).add(off);camera.lookAt(look);const idx=R.race.t<R.race.green+9?R.leader():focus,q=sample(R.cars[idx].s,R.cars[idx].lane);sun.target.position.copy(q.p);sun.position.copy(q.p).add(v3(380,620,220));sun.target.updateMatrixWorld();return idx;}
 function setMode(m){mode=m;ready=false;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));camEl.textContent=(m==='AUTO'?`AUTO · ${auto}`:m)+' · SWIPE';}
 function move(x,y){if(!drag)return;const dx=x-lastX,dy=y-lastY;lastX=x;lastY=y;yaw=clamp(yaw-dx*.0065,-Math.PI,Math.PI);pitch=clamp(pitch-dy*.0048,-.52,.58);}
 renderer.domElement.addEventListener('touchstart',e=>{if(e.touches.length!==1)return;e.preventDefault();const t=e.touches[0],n=performance.now();if(n-lastTap<320){yaw=0;pitch=0;}lastTap=n;drag=true;lastX=t.clientX;lastY=t.clientY;},{passive:false});renderer.domElement.addEventListener('touchmove',e=>{if(e.touches.length!==1)return;e.preventDefault();move(e.touches[0].clientX,e.touches[0].clientY);},{passive:false});renderer.domElement.addEventListener('touchend',()=>drag=false,{passive:true});
 renderer.domElement.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')return;drag=true;lastX=e.clientX;lastY=e.clientY;renderer.domElement.setPointerCapture?.(e.pointerId);});renderer.domElement.addEventListener('pointermove',e=>{if(e.pointerType!=='touch')move(e.clientX,e.clientY);});renderer.domElement.addEventListener('pointerup',()=>drag=false);
 document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));document.getElementById('next').addEventListener('click',()=>{focus=(focus+1)%R.cars.length;ready=false;});document.getElementById('prev').addEventListener('click',()=>{focus=(focus-1+R.cars.length)%R.cars.length;ready=false;});camEl.textContent='AUTO · TV · SWIPE';return{update};
}
