export function createRace(W,statusEl){
 const T=W.THREE,{clamp,wrap,total,sample,braking}=W,colors=[0xf23b35,0x2f7fe8,0xffce32,0xf3f3f3,0x18c982,0x9d62ef,0xf57c22,0x1eb9c5,0xf24f9a,0xb7bdc6],types=['formula','gt','proto'],cars=[],laneLimit=3.9;
 for(let i=0;i<20;i++){const type=types[i%3],mesh=W.makeCar(colors[i%colors.length],type),d=mesh.userData.dims;W.scene.add(mesh);const row=Math.floor(i/2),col=i%2,lane=(col?-1:1)*2.55+(row%2?.14:-.14),skill=.94+((i*7)%13)*.006;cars.push({mesh,type,length:d.length,width:d.width,s:wrap(-row*12.4,total),lane,laneTarget:lane,v:0,prevV:0,brakeVisual:0,max:(type==='formula'?79:type==='gt'?73:76)*skill,accel:(type==='formula'?6.9:type==='gt'?6.1:6.5)+skill*.7,brake:16.5,lap:0,overtake:0,avoid:0,reaction:.10+Math.random()*.55,launch:1+Math.random()*.09,wheelSpin:0});}
 const gap=(a,b)=>wrap(b.s-a.s,total),ahead=(c,idx)=>{let car=null,g=1e9;for(let j=0;j<cars.length;j++)if(j!==idx){const q=gap(c,cars[j]);if(q<g){g=q;car=cars[j];}}return{car,g};};
 function laneClear(idx,target,aheadDist=44,behindDist=20){const me=cars[idx];for(let j=0;j<cars.length;j++)if(j!==idx){const o=cars[j],ga=gap(me,o),gb=gap(o,me),lat=Math.abs(o.lane-target),min=(me.width+o.width)*.42+.45;if((ga<aheadDist||gb<behindDist)&&lat<min)return false;}return true;}
 function laneScore(idx,target){const me=cars[idx];let score=0;for(let j=0;j<cars.length;j++)if(j!==idx){const o=cars[j],ga=gap(me,o),gb=gap(o,me),lat=Math.abs(o.lane-target);if(ga<60)score+=Math.min(24,ga)*.26+lat*1.9;if(gb<24)score+=Math.min(14,gb)*.18+lat*1.5;}return score-Math.abs(target)*.08;}
 function chooseLane(idx){const c=[-3.25,3.25].filter(x=>laneClear(idx,x));if(!c.length)return null;c.sort((a,b)=>laneScore(idx,b)-laneScore(idx,a));return c[0];}
 function pose(c){const q=sample(c.s,c.lane);c.mesh.position.copy(q.p);c.mesh.position.y+=.12;c.mesh.rotation.y=Math.atan2(q.t.x,q.t.z);const vis=c.mesh.userData.visual;if(vis)vis.rotation.x=T.MathUtils.lerp(vis.rotation.x,c.brakeVisual*.045,.22);c.wheelSpin+=c.v*.018;for(const w of c.mesh.userData.wheels||[])w.rotation.x=c.wheelSpin;for(const m of c.mesh.userData.brakeMats||[])m.emissiveIntensity=.05+c.brakeVisual*2.8;}
 function separate(){for(let i=0;i<cars.length;i++)for(let j=i+1;j<cars.length;j++){const a=cars[i],b=cars[j],ga=gap(a,b),gb=gap(b,a),f=ga<gb?ga:-gb,ad=Math.abs(f),lat=b.lane-a.lane,minL=(a.length+b.length)*.48+.75,minW=(a.width+b.width)*.31;if(ad<minL&&Math.abs(lat)<minW){const dir=(lat||((i+j)%2?1:-1))>0?1:-1,p=(minW-Math.abs(lat)+.05)*.38;a.lane=clamp(a.lane-dir*p,-laneLimit,laneLimit);b.lane=clamp(b.lane+dir*p,-laneLimit,laneLimit);if(f>0){a.v=Math.min(a.v,b.v*.97);a.s=wrap(a.s-(minL-ad)*.28,total);}else{b.v=Math.min(b.v,a.v*.97);b.s=wrap(b.s-(minL-ad)*.28,total);}}}}
 cars.forEach(pose);const race={t:0,green:4};
 function update(dt){race.t+=dt;if(race.t<race.green){statusEl.textContent='LIGHTS '+Math.max(1,Math.ceil(race.green-race.t));cars.forEach(pose);return;}statusEl.textContent=race.t<race.green+.6?'GREEN':'RUNNING';for(let i=0;i<cars.length;i++){const c=cars[i],load=braking(c.s);let target=Math.max(21,c.max*(1-.70*load));if(race.t<race.green+c.reaction)target=0;else if(race.t<race.green+4.5)target=Math.max(target,c.max*.82*c.launch);const f=ahead(c,i);if(f.car){const lat=Math.abs(f.car.lane-c.lane),overlap=lat<(c.width+f.car.width)*.43+.35,closing=Math.max(0,c.v-f.car.v),safe=(c.length+f.car.length)*.55+4.5,ttc=closing>.5?(f.g-safe)/closing:99;if(overlap&&f.g<115&&f.g>32)target*=1.035;if(overlap&&(f.g<40||ttc<2.35)){const opt=(c.avoid<=0&&load<.58)?chooseLane(i):null;if(opt!==null){c.laneTarget=opt;c.avoid=1.9;c.overtake=2.9;}const margin=clamp((f.g-safe)/20,0,1);target=Math.min(target,f.car.v+margin*7);if(ttc<1.25||f.g<safe+4)target=Math.min(target,f.car.v*.97);}}
 for(let j=0;j<cars.length;j++)if(j!==i){const o=cars[j],long=Math.min(gap(c,o),gap(o,c));if(long<11){const min=(c.width+o.width)*.5+.6,lat=c.lane-o.lane;if(Math.abs(lat)<min){const away=lat>=0?1:-1;c.laneTarget=clamp(c.laneTarget+away*(min-Math.abs(lat))*.30,-laneLimit,laneLimit);target=Math.min(target,c.max*.94);}}}
 if(c.avoid>0)c.avoid-=dt;if(c.overtake>0)c.overtake-=dt;else if(load>.46&&c.avoid<=0)c.laneTarget*=.90;else if(c.avoid<=0)c.laneTarget*=.997;c.laneTarget=clamp(c.laneTarget,-laneLimit,laneLimit);const dv=target-c.v,rate=dv>0?c.accel:c.brake;c.prevV=c.v;c.v+=clamp(dv,-rate*dt,rate*dt);const dec=Math.max(0,(c.prevV-c.v)/Math.max(dt,.001));c.brakeVisual=T.MathUtils.lerp(c.brakeVisual,clamp(dec/12,0,1),1-Math.exp(-8*dt));c.lane=T.MathUtils.lerp(c.lane,c.laneTarget,1-Math.exp(-2.1*dt));const old=c.s;c.s=wrap(c.s+c.v*dt,total);if(c.s<old-total*.5)c.lap++;}separate();cars.forEach(pose);}
 function leader(){let bi=0,bs=-1e9;for(let i=0;i<cars.length;i++){const s=cars[i].lap*total+cars[i].s;if(s>bs){bs=s;bi=i;}}return bi;}
 return{cars,race,update,leader};
}
