export function createUI(W,R,D,E,C){
  const style=document.createElement('style');style.textContent=`
  #hud{max-width:255px;padding:7px 9px;font-size:11px;background:#07121bb8;border-color:#ffffff24}
  #cam,#controls{display:none}body.v8-cam #cam{display:block}body.v8-cam #controls{display:flex}
  #v8MenuBtn{position:fixed;z-index:60;right:10px;top:max(10px,env(safe-area-inset-top));width:42px;height:36px;min-width:42px;padding:0;border-radius:10px;background:#07121bd8;border:1px solid #ffffff30;font-size:18px}
  #v8Drawer{display:none;position:fixed;z-index:55;right:10px;top:max(54px,calc(env(safe-area-inset-top) + 44px));width:min(84vw,330px);max-height:72vh;overflow:hidden;background:#07121be8;border:1px solid #ffffff2c;border-radius:14px;backdrop-filter:blur(12px);box-shadow:0 10px 32px #0007}
  #v8Drawer.open{display:block}#v8Tabs{display:flex;gap:4px;padding:7px;overflow-x:auto;border-bottom:1px solid #ffffff18}#v8Tabs button{height:31px;min-width:48px;padding:0 7px;font-size:9px;border-radius:7px;white-space:nowrap}#v8Tabs button.on{background:#fff;color:#07121b}
  #v8Body{max-height:calc(72vh - 46px);overflow:auto;padding:8px;font-size:10px;line-height:1.35}.v8head{display:flex;justify-content:space-between;font-weight:950;margin-bottom:5px}.v8row{display:grid;grid-template-columns:20px 1fr 42px 36px;gap:4px;align-items:center;padding:4px 0;border-top:1px solid #ffffff12}.v8row.me{color:#65ff9a}.muted{color:#aeb8c0}.good{color:#65ff9a}.warn{color:#ffd35f}.bad{color:#ff7373}.section{padding:6px 0;border-top:1px solid #ffffff16}.section:first-child{border-top:0}.section b{color:#fff}.tag{display:inline-block;padding:2px 5px;border-radius:5px;background:#ffffff14;margin:1px 2px 1px 0;font-size:9px;font-weight:850}
  #trackMap{width:100%;aspect-ratio:1.42;background:#081017;border-radius:10px;border:1px solid #ffffff18;touch-action:manipulation}
  #eventBanner{position:fixed;z-index:50;top:max(58px,calc(env(safe-area-inset-top) + 52px));left:50%;transform:translateX(-50%);padding:7px 13px;border-radius:8px;background:#0b121ce8;border:1px solid #ffffff38;font-size:12px;font-weight:950;letter-spacing:.5px;opacity:0;transition:opacity .15s;white-space:nowrap;pointer-events:none}#eventBanner.show{opacity:1}#eventBanner.yellow{background:#8a6a00ed}#eventBanner.sc{background:#9a6d00ed}#eventBanner.fault{background:#8d2020ed}
  #v8Zoom{display:none;position:fixed;z-index:61;right:10px;bottom:calc(max(72px,env(safe-area-inset-bottom) + 62px));grid-template-columns:repeat(3,42px);gap:5px}body.v8-cam #v8Zoom{display:grid}#v8Zoom button{min-width:42px;width:42px;height:38px;padding:0;font-size:18px;background:#07121be6}
  #nextRoundBtn{width:100%;height:36px;margin-top:8px;background:#ffffff18;border:1px solid #ffffff30;border-radius:8px;color:#fff;font-weight:900}
  @media(max-width:430px){#controls{left:8px;right:8px;transform:none;justify-content:center;overflow-x:auto}#controls button{min-width:44px;padding:0 7px}#v8Drawer{width:calc(100vw - 20px)}}
  `;document.head.appendChild(style);

  const btn=document.createElement('button');btn.id='v8MenuBtn';btn.textContent='☰';document.body.appendChild(btn);
  const drawer=document.createElement('div');drawer.id='v8Drawer';drawer.innerHTML='<div id="v8Tabs"><button data-v="race" class="on">RACE</button><button data-v="map">MAP</button><button data-v="data">DATA</button><button data-v="series">SERIES</button><button data-v="radio">RADIO</button><button data-v="cam">CAM</button></div><div id="v8Body"></div>';document.body.appendChild(drawer);
  const body=drawer.querySelector('#v8Body'),tabs=drawer.querySelector('#v8Tabs');
  const banner=document.createElement('div');banner.id='eventBanner';document.body.appendChild(banner);
  const zoom=document.createElement('div');zoom.id='v8Zoom';zoom.innerHTML='<button data-z="in">＋</button><button data-z="out">−</button><button data-z="reset">↺</button>';document.body.appendChild(zoom);
  zoom.querySelector('[data-z="in"]').onclick=C.zoomIn;zoom.querySelector('[data-z="out"]').onclick=C.zoomOut;zoom.querySelector('[data-z="reset"]').onclick=C.reset;
  let opened=false,view='race',focusId=0,acc=0,mapCanvas=null,mapCars=[];
  btn.onclick=()=>{opened=!opened;drawer.classList.toggle('open',opened);btn.textContent=opened?'×':'☰';if(!opened){document.body.classList.remove('v8-cam');}};
  tabs.addEventListener('click',e=>{const b=e.target.closest('[data-v]');if(!b)return;view=b.dataset.v;tabs.querySelectorAll('button').forEach(x=>x.classList.toggle('on',x===b));document.body.classList.toggle('v8-cam',view==='cam');render(true);});
  drawer.addEventListener('click',e=>{if(e.target.id==='nextRoundBtn')R.nextRound();});

  const fmt=t=>!Number.isFinite(t)?'--':`${Math.floor(t/60)}:${(t%60).toFixed(3).padStart(6,'0')}`;
  const fmtS=t=>!Number.isFinite(t)?'--':`${t.toFixed(3)}s`;
  const colour=n=>`#${(n>>>0).toString(16).padStart(6,'0')}`;
  const tyreColor=c=>R.compounds?.[c]?.color||'#fff';
  const track=[];for(let i=0;i<220;i++){const p=W.sample(W.total*i/220).p;track.push([p.x,p.z]);}
  const xs=track.map(p=>p[0]),zs=track.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minZ=Math.min(...zs),maxZ=Math.max(...zs);
  function mapPoint(x,z,w,h){const pad=18,s=Math.min((w-pad*2)/(maxX-minX),(h-pad*2)/(maxZ-minZ));return[pad+(x-minX)*s,h-pad-(z-minZ)*s];}
  function drawTrackMap(){
    if(!mapCanvas)return;const dpr=Math.min(devicePixelRatio||1,2),rect=mapCanvas.getBoundingClientRect(),w=Math.max(260,rect.width),h=w/1.42;mapCanvas.width=w*dpr;mapCanvas.height=h*dpr;const g=mapCanvas.getContext('2d');g.setTransform(dpr,0,0,dpr,0,0);g.clearRect(0,0,w,h);
    g.lineJoin='round';g.lineCap='round';g.strokeStyle='#2a333a';g.lineWidth=7;g.beginPath();track.forEach(([x,z],i)=>{const [px,py]=mapPoint(x,z,w,h);i?g.lineTo(px,py):g.moveTo(px,py)});g.closePath();g.stroke();g.strokeStyle='#b8c0c4';g.lineWidth=2;g.stroke();
    for(const [a,b] of R.drsZones||[]){g.strokeStyle='#54df79';g.lineWidth=4;g.beginPath();for(let k=0;k<=24;k++){const f=a+(b-a)*k/24,p=W.sample(W.total*(f>=1?f-1:f)).p,[x,y]=mapPoint(p.x,p.z,w,h);k?g.lineTo(x,y):g.moveTo(x,y);}g.stroke();}
    mapCars=[];for(const c of R.cars){if(c.retired)continue;const p=W.sample(c.s,c.lane).p,[x,y]=mapPoint(p.x,p.z,w,h);mapCars.push({id:c.id,x,y});g.beginPath();g.fillStyle=colour(c.teamColor||0xffffff);g.arc(x,y,c.id===focusId?5.2:3.7,0,Math.PI*2);g.fill();if(c.id===focusId){g.strokeStyle='#fff';g.lineWidth=1.5;g.stroke();}}
  }
  function bindMap(){if(!mapCanvas)return;mapCanvas.onclick=e=>{const r=mapCanvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;let best=null,d=1e9;for(const p of mapCars){const q=(p.x-x)**2+(p.y-y)**2;if(q<d){d=q;best=p;}}if(best&&d<625){focusId=best.id;C.setFocus(best.id);drawTrackMap();}};}

  function raceHTML(){const st=R.getStandings(),lead=st[0],lap=Math.min((lead?.lap||0)+1,R.race.lapsTarget);let h=`<div class="v8head"><span>${R.sessionPhase==='QUALIFYING'?'QUALIFYING':`LAP ${lap}/${R.race.lapsTarget}`}</span><span>${R.flag}</span></div>`;if(R.sessionPhase==='QUALIFYING'){R.qualifying.forEach((q,i)=>{const c=R.cars[q.carId];h+=`<div class="v8row ${c.id===focusId?'me':''}"><b>${i+1}</b><span>${c.name} <span class="muted">${c.team}</span></span><span>${q.time.toFixed(3)}</span><span>Q</span></div>`;});return h;}st.forEach(c=>{const gap=c===lead?'LEAD':`+${Math.max(0,((lead.lap*W.total+lead.s)-(c.lap*W.total+c.s))/Math.max(1,lead.v)).toFixed(1)}s`;h+=`<div class="v8row ${c.id===focusId?'me':''}"><b>${c.position}</b><span>${c.name} <span class="muted">${c.team}</span></span><span>${gap}</span><span style="color:${tyreColor(c.compound)}">${c.compound[0]}${Math.round(c.wear*100)}</span></div>`;});return h;}
  function dataHTML(){const c=R.cars[focusId]||R.getStandings()[0];if(!c)return'';const gb=R.globalBestSectors||[];return `<div class="section"><b>${c.name} · ${c.team}</b><br>P${c.position} · ${c.type.toUpperCase()} · ${Math.round(c.v*3.6)} km/h<br><span class="tag ${c.drsActive?'good':''}">DRS ${c.drsActive?'ACTIVE':c.drsEligible?'READY':'OFF'}</span><span class="tag">${c.battleState}</span>${c.fault?`<span class="tag bad">${c.fault}</span>`:''}</div><div class="section"><b>MACHINE</b><br>POWER ${Math.round(c.machine.power*100)} · AERO ${Math.round(c.machine.aero*100)} · BRAKE ${Math.round(c.machine.brake*100)}<br>TYRE ${Math.round(c.machine.tyre*100)} · REL ${Math.round(c.machine.reliability*1000)/10}%</div><div class="section"><b>SECTORS</b><br>S1 ${fmtS(c.lastSectors[0])} <span class="muted">BEST ${fmtS(c.bestSectors[0])} / ${fmtS(gb[0])}</span><br>S2 ${fmtS(c.lastSectors[1])} <span class="muted">BEST ${fmtS(c.bestSectors[1])} / ${fmtS(gb[1])}</span><br>S3 ${fmtS(c.lastSectors[2])} <span class="muted">BEST ${fmtS(c.bestSectors[2])} / ${fmtS(gb[2])}</span><br>LAP BEST ${fmt(c.bestLap)}</div><div class="section"><b>DRIVER</b><br>AGG ${Math.round(c.driver.aggression*100)} · RACECRAFT ${Math.round(c.driver.racecraft*100)}<br>TYRE ${Math.round(c.driver.tireCare*100)} · WET ${Math.round(c.driver.wetSkill*100)}</div>`;}
  function seriesHTML(){const ch=R.championship;let h=`<div class="section"><b>CHAMPIONSHIP · ROUND ${ch.roundNumber}/${ch.rounds}</b><br>${ch.roundName}</div><div class="section"><b>DRIVERS</b>`;ch.drivers.slice(0,10).forEach((d,i)=>h+=`<div class="v8row"><b>${i+1}</b><span>${d.name} <span class="muted">${d.team}</span></span><span>${d.points}</span><span>PTS</span></div>`);h+='</div><div class="section"><b>TEAMS</b>';ch.teams.forEach((t,i)=>h+=`<div class="v8row"><b>${i+1}</b><span style="color:${colour(t.color)}">${t.name}</span><span>${t.points}</span><span>PTS</span></div>`);h+='</div><div class="section"><b>QUALIFYING TOP 5</b>';R.qualifying.slice(0,5).forEach((q,i)=>{const c=R.cars[q.carId];h+=`<br>P${i+1} ${c.name} · ${q.time.toFixed(3)}`;});h+='</div>';if(ch.awarded)h+=`<button id="nextRoundBtn">${ch.isFinal?'RESET SEASON':'NEXT ROUND'}</button>`;return h;}
  function radioHTML(){const r=[...(R.radio||[])].reverse();if(!r.length)return'<div class="muted">No radio messages yet.</div>';return r.map(x=>`<div class="section"><b>${x.name}</b> <span class="muted">${x.kind}</span><br>${x.text}</div>`).join('');}
  function camHTML(){return'<div class="section"><b>CAMERA</b><br>1本指ドラッグ: 360°回転<br>2本指ピンチ: ズーム<br>ダブルタップ: リセット<br><br>下部の TV / CHASE / HELI / AUTO で切替。右下の ＋ / − / ↺ でもズーム操作できます。</div>';}
  function mapHTML(){return'<div class="section"><b>LIVE TRACK MAP</b><br><span class="muted">車の点をタップすると追従対象を変更</span></div><canvas id="trackMap"></canvas><div class="section muted">緑線: DRSゾーン</div>';}
  function render(force=false){if(!opened&&!force)return;body.innerHTML=view==='race'?raceHTML():view==='data'?dataHTML():view==='series'?seriesHTML():view==='radio'?radioHTML():view==='cam'?camHTML():mapHTML();if(view==='map'){mapCanvas=body.querySelector('#trackMap');bindMap();requestAnimationFrame(drawTrackMap);}else mapCanvas=null;}
  function update(dt,id){focusId=id;acc+=dt;if(acc<.18)return;acc=0;if(opened)render();let text=D.banner,cls='';if(R.flag==='SC'){text='SAFETY CAR';cls='sc';}else if(R.flag==='YELLOW'){text='YELLOW FLAG';cls='yellow';}else if(text&&(/ENGINE|BRAKE|PUNCTURE|ELECTRICAL|RETIRED/.test(text)))cls='fault';banner.textContent=text||'';banner.className=text?`show ${cls}`:'';}
  return{update};
}
