import {createRace as createV20Race} from './v20-race.js';

export function createRace(W,statusEl,settings={}){
  const R=createV20Race(W,statusEl,settings),baseUpdate=R.update,total=Math.max(1,W.total||1);
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),wrap=v=>((v%total)+total)%total;
  const hybridTypes=new Set(['formula','hyper','lmh','proto']),isHybrid=t=>hybridTypes.has(t),wheelNames=['FL','FR','RL','RR'];
  const stewardCases=[],neighbourCache=new Map(),activeCars=[],prevPosById=[],prevProgressById=[];
  let strategyClock=0,driverClock=0,prevFlag=R.flag,restartLock=0,caseId=0,standingsCache=[];
  R.trackEvolution={rubber:.08,marbles:0,dryLine:0};
  const event=(type,car,data={})=>{R.events?.push({id:`systems-${Date.now()}-${Math.random()}`,type,t:R.race.t,carId:car?.id??null,data});if(R.events?.length>120)R.events.shift();};
  const radio=(car,text,kind='ENGINEER_AI')=>{if(!R.radio)return;R.radio.push({id:`systemsr-${Date.now()}-${Math.random()}`,t:R.race.t,carId:car?.id??null,name:car?.name||'RACE CONTROL',text,kind});while(R.radio.length>36)R.radio.shift();};
  const progress=c=>c?._v8Progress??((c?.lap||0)*total+(c?.s||0));
  for(const c of R.cars){c.energyMode='BALANCED';c.ers=isHybrid(c.type)?1:0;c.liftCoast=0;c.slipstream=0;c.dirtyAir=0;c.wheelState=wheelNames.map(name=>({name,temp:c.tyreTemp||86,wear:c.wear||0,brake:c.brakeTemp||320,flat:0,puncture:false,nutIssue:false}));c.strategy={plan:'ONE STOP',window:'--',reason:'BASELINE',pitLoss:22,undercut:0,overcut:0,freeStop:false};c.driverState={confidence:.72,morale:.72,pressure:.28,fatigue:0};neighbourCache.set(c.id,{aheadView:{car:null,dist:Infinity},behindView:{car:null,dist:Infinity}});}
  function refreshNeighbours(){standingsCache=R.getStandings();activeCars.length=0;for(const c of R.cars)if(!c.retired&&c.pitState==='NONE')activeCars.push(c);activeCars.sort((a,b)=>(a.s||0)-(b.s||0));const n=activeCars.length;for(const c of R.cars){const rec=neighbourCache.get(c.id);if(rec){rec.aheadView.car=null;rec.aheadView.dist=Infinity;rec.behindView.car=null;rec.behindView.dist=Infinity;}}if(n<2)return;for(let i=0;i<n;i++){const c=activeCars[i],a=activeCars[(i+1)%n],b=activeCars[(i-1+n)%n],rec=neighbourCache.get(c.id);rec.aheadView.car=a;rec.aheadView.dist=wrap((a.s||0)-(c.s||0));rec.behindView.car=b;rec.behindView.dist=wrap((c.s||0)-(b.s||0));}}
  const emptyAhead={car:null,dist:Infinity},emptyBehind={car:null,dist:Infinity};
  const aheadOf=c=>neighbourCache.get(c.id)?.aheadView||emptyAhead,behindOf=c=>neighbourCache.get(c.id)?.behindView||emptyBehind;
  function strategyUpdate(){const st=standingsCache.length?standingsCache:R.getStandings(),wet=W.env?.wetness||0,flag=R.flag;for(const c of st){if(c.retired)continue;const a=aheadOf(c),b=behindOf(c),lapsLeft=Math.max(0,(R.race?.lapsTarget||0)-(c.lap||0)),fuel=clamp(Number(c.fuel)||0,0,1),tyreLife=Math.max(.2,(1-(c.wear||0))/Math.max(.01,.018+(c.driverFatigue||0)*.004)),cheap=flag==='SC'||flag==='VSC',needWet=wet>.44&&c.compound!=='WET',needDry=wet<.18&&c.compound==='WET',worn=(c.wear||0)>.70,gapAhead=a.car?a.dist/Math.max(10,c.v):99,gapBehind=b.car?b.dist/Math.max(10,b.car.v):99,undercut=gapAhead<3.2&&gapBehind>2.2&&c.wear>.48?clamp((3.2-gapAhead)/3.2,0,1):0,overcut=gapAhead<4&&c.wear<.48?clamp((.5-c.wear)*1.8,0,1):0;c.strategy.undercut=undercut;c.strategy.overcut=overcut;c.strategy.freeStop=cheap;c.strategy.window=tyreLife<lapsLeft?'OPEN':'EXTEND';c.strategy.reason=cheap?'SAFETY CAR WINDOW':needWet?'RAIN CROSSOVER':needDry?'DRY CROSSOVER':worn?'TYRE LIFE':fuel<.10?'FUEL':undercut>.55?'UNDERCUT ATTACK':overcut>.55?'OVERCUT':'BASELINE';if(c.pitState==='NONE'&&c.lap>0&&c.s>total*.72&&(needWet||needDry||worn||(cheap&&c.wear>.45)||undercut>.72||(fuel<.07&&c.type!=='formula'))){c.pitState='ENTRY';radio(c,`Box this lap. ${c.strategy.reason.toLowerCase()}.`,'STRATEGY');event('STRATEGY_CALL',c,{reason:c.strategy.reason});}const battle=gapAhead<2.2||gapBehind<1.6;c.energyMode=(lapsLeft<=2||(battle&&c.ers>.35))?'PUSH':(c.ers<.18||fuel<.18?'SAVE':'BALANCED');}}
  function energyAndTraffic(c,dt){if(c.retired||c.pitState!=='NONE'){c.slipstream=0;c.dirtyAir=0;return;}const load=clamp(W.braking?.(c.s)||0,0,1),a=aheadOf(c),straight=1-load,hybrid=isHybrid(c.type);let slip=0,dirty=0;if(a.car){const lat=Math.abs((a.car.lane||0)-(c.lane||0));if(a.dist<55&&lat<3){slip=clamp((55-a.dist)/50,0,1)*straight;dirty=clamp((30-a.dist)/25,0,1)*load*(c.type==='formula'?1:hybrid?.65:.32);}}c.slipstream=slip;c.dirtyAir=dirty;const mode=c.energyMode==='PUSH'?1:c.energyMode==='SAVE'?-1:0;if(hybrid){const deploy=(.010+.010*Math.max(0,mode))*dt*(.35+.65*straight),regen=(.006+.017*load)*dt;c.ers=clamp(c.ers-deploy+regen,0,1);c.hybridCharge=c.ers;}c.liftCoast=c.energyMode==='SAVE'?clamp(.14+Math.max(0,.25-(c.fuel||0)),.14,.30):0;}
  function wheelPhysics(c,dt){if(c.retired)return;const k=Number(W.racingCurvatureAt?.(c.s)??W.curvatureAt?.(c.s))||0,latAccel=(c.v||0)*(c.v||0)*k,turn=Math.sign(k),brake=clamp(c.racingBrake??c.brakeVisual??0,0,1),wet=W.env?.wetness||0;for(let i=0;i<4;i++){const w=c.wheelState[i],front=i<2,left=i%2===0,isOuter=turn===0?false:(turn>0?!left:left),outer=turn===0?0:(isOuter?1:-1),load=Math.min(1,Math.abs(latAccel)/(3.5*9.81)),target=(c.tyreTemp||86)+(front?brake*8:brake*3)+outer*5*load+load*3-wet*3;w.temp+=(target-w.temp)*(1-Math.exp(-.55*dt));w.brake+=((c.brakeTemp||320)+(front?80:25)*brake-w.brake)*(1-Math.exp(-1.1*dt));w.wear=clamp(Math.max(w.wear,c.wear||0)+(outer>0?load*.00003*dt:0),0,1);if(c.spinState==='LOCKUP'&&front)w.flat=clamp(w.flat+dt*.08,0,1);if(c.flatSpot)w.flat=Math.max(w.flat,.25);if(w.puncture)c.v=Math.min(c.v,18);}}
  function evolveTrack(dt){const s=W.surfaceState||{},wet=clamp(W.env?.wetness||0,0,1),e=R.trackEvolution;e.rubber=s.rubber??clamp(e.rubber+dt*(wet<.2?.0004:.00005),0,1);e.dryLine=s.dryLine??e.rubber*(1-wet*.75);e.marbles=clamp(e.marbles+dt*.00018*(1-wet),0,.55);for(const c of R.cars){if(c.retired)continue;const ideal=W.racingLineAt?.(c.s)??0,deviation=Math.abs((c.lane||0)-ideal),off=clamp((deviation-1.2)/2.35,0,1);c.trackEvolutionGrip=1+e.dryLine*.018*(1-off)-e.marbles*.055*off;}}
  function driverDynamics(c,dt){const d=c.driverState;if(!d||c.retired)return;d.fatigue=clamp(d.fatigue+dt/7200*(.9+(c.driver?.aggression||.6)*.2),0,1);c.driverFatigue=d.fatigue;const posGain=clamp((10-(c.position||10))/20,-.2,.35),a=aheadOf(c),b=behindOf(c);d.confidence=clamp(d.confidence+(posGain-d.pressure*.12)*dt*.002,0,1);d.pressure=clamp(.15+(c.position<=3?.20:0)+(a.dist<18?.28:0)+(b.dist<14?.30:0)+d.fatigue*.18,0,1);d.morale=clamp(d.morale+(d.confidence-.5)*dt*.0015,0,1);if(c.driver)c.driver.aggression=clamp((c.driver.aggression||.6)+((d.confidence-.5)-(d.pressure-.5))*.0008,.35,.96);}
  function addCase(type,car,other,severity=.5){const item={id:++caseId,type,carId:car?.id??null,otherId:other?.id??null,t:R.race.t,status:'NOTED',timer:2.5+severity*3,severity};stewardCases.push(item);if(stewardCases.length>30)stewardCases.shift();event('INCIDENT_NOTED',car,{caseId:item.id,type});return item;}
  function stewardUpdate(dt){for(const x of stewardCases){if(x.status==='CLOSED')continue;x.timer-=dt;if(x.status==='NOTED'&&x.timer<1.8){x.status='INVESTIGATING';event('UNDER_INVESTIGATION',R.cars[x.carId],{caseId:x.id,type:x.type});}if(x.timer<=0){const c=R.cars[x.carId];let sec=0;if(x.type==='CAUSING_COLLISION')sec=x.severity>.75?10:5;else if(x.type==='UNSAFE_RELEASE')sec=5;if(c&&sec){c.penaltySeconds=(c.penaltySeconds||0)+sec;radio(c,`${sec} second penalty. ${x.type.toLowerCase().replaceAll('_',' ')}.`,'PENALTY');event('PENALTY',c,{seconds:sec,reason:x.type});}x.status='CLOSED';}}}
  function restartRules(dt){if(prevFlag==='SC'&&R.flag==='GREEN'){restartLock=3.2;event('SC_RESTART_RULES',null,{seconds:restartLock});}if(restartLock>0)restartLock=Math.max(0,restartLock-dt);prevFlag=R.flag;}
  function yellowOvertakes(){if(!['YELLOW','SC','VSC'].includes(R.flag))return;for(const c of R.cars){const prev=prevPosById[c.id],pp=prevProgressById[c.id];if(!Number.isFinite(prev)||!Number.isFinite(pp)||c.retired||c.pitState!=='NONE'||c.spinState!=='NONE')continue;if(c.position<prev&&progress(c)>pp+2&&c._explicitYellowPassViolation){if(!stewardCases.some(x=>x.type==='YELLOW_OVERTAKE'&&x.carId===c.id&&x.status!=='CLOSED'))addCase('YELLOW_OVERTAKE',c,null,.45);}}}
  function update(dt){const step=clamp(Number(dt)||.016,.001,.05);for(const c of R.cars){prevPosById[c.id]=c.position;prevProgressById[c.id]=progress(c);}baseUpdate(step);refreshNeighbours();evolveTrack(step);strategyClock+=step;driverClock+=step;if(strategyClock>=1.2){strategyClock-=1.2;strategyUpdate();}for(const c of R.cars){energyAndTraffic(c,step);wheelPhysics(c,step);if(driverClock>=.5)driverDynamics(c,.5);}if(driverClock>=.5)driverClock-=.5;yellowOvertakes();stewardUpdate(step);restartRules(step);}
  refreshNeighbours();
  return new Proxy(R,{get(target,prop){if(prop==='update')return update;if(prop==='getStandings')return()=>standingsCache;if(prop==='leader')return()=>standingsCache[0]?.id??0;if(prop==='stewardCases')return stewardCases;if(prop==='trackEvolution')return R.trackEvolution;if(prop==='spatialNeighbours')return neighbourCache;if(prop==='standingsCache')return standingsCache;return Reflect.get(target,prop,target);}});
}
