import {createRace as createV25Race} from './v25-race.js';

export function createRace(W,statusEl,settings={}){
  const physicalSCEnabled=settings.safetyCar!==false,R=createV25Race(W,statusEl,{...settings,safetyCar:false}),baseUpdate=R.update,total=Math.max(1,W.total||1);
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),wrap=v=>((v%total)+total)%total,trackDist=(a,b)=>{const d=Math.abs(wrap(a-b));return Math.min(d,total-d);},progress=c=>c?._v8Progress??((c?.lap||0)*total+(c?.s||0));
  const seen=new Set(),reviews=[],localYellows=[],monitors=new Map(),sector=new Map(),calibration=new Map(),globalBest=[Infinity,Infinity,Infinity],vscState=new Map();let reviewId=0,scCount=0,scCooldownUntil=0;
  const caution={type:'GREEN',reason:'',carId:null,startedAt:0,minUntil:0,severity:0,freeze:null,order:null};
  const emit=(type,car,data={})=>{R.events?.push({id:`control-${Date.now()}-${Math.random()}`,type,t:R.race.t,carId:car?.id??null,data});while(R.events?.length>150)R.events.shift();};
  const radio=(car,text,kind='CONTROL')=>{if(!R.radio)return;R.radio.push({id:`controlr-${Date.now()}-${Math.random()}`,t:R.race.t,carId:car?.id??null,name:car?.name||'RACE CONTROL',text,kind});while(R.radio.length>42)R.radio.shift();};
  const sectorOf=c=>Math.min(2,Math.floor(clamp((c?.s||0)/total,0,.999999)*3)),baseTargets={formula:[91,98],hyper:[105,115],lmh:[105,115],proto:[103,114],gt:[118,128],supercar:[120,132],touring:[128,145]},trackScale=clamp(total/5807,.65,1.35),targetFor=type=>(baseTargets[type]||baseTargets.gt).map(x=>x*trackScale);
  for(const c of R.cars){sector.set(c.id,{current:sectorOf(c),start:R.race.t,last:[null,null,null],best:[Infinity,Infinity,Infinity],deltaPersonal:[null,null,null],deltaOverall:[null,null,null],status:['--','--','--']});calibration.set(c.id,{samples:[],factor:1,average:null,target:targetFor(c.type),lastLapSeen:null});c.radarForecast={now:0,in60:0,in180:0};}
  function effectiveFlag(){return caution.type!=='GREEN'?caution.type:(R.flag||'GREEN');}
  function addLocalYellow(car,reason='INCIDENT',duration=6,radius=145){if(!car)return;localYellows.push({id:`ly-${Date.now()}-${Math.random()}`,s:car.s,carId:car.id,reason,expires:R.race.t+duration,radius});emit('LOCAL_YELLOW',car,{reason,radius});}
  function activeRecovery(){return(W.activeRecoveries?.()||[]).length>0;}
  function startRecovery(car,reason){if(!car||W.recoveryActive?.(car.id))return;W.spawnRecovery?.(car,reason);emit('RECOVERY_STARTED',car,{reason});}
  function freezeCars(){return R.cars.map(c=>({id:c.id,s:c.s,lane:c.lane,laneTarget:c.laneTarget,lap:c.lap,progress:c._v8Progress,v:c.v}));}
  function restoreFrozen(){if(!caution.freeze)return;for(const x of caution.freeze){const c=R.cars[x.id];if(!c||c.retired)continue;c.s=x.s;c.lane=x.lane;c.laneTarget=x.laneTarget;c.lap=x.lap;c._v8Progress=x.progress;c.v=0;c.drsActive=false;c.drsEligible=false;c.overtake=0;const q=W.sample(c.s,c.lane);c.mesh?.position?.copy?.(q.p);if(c.mesh?.position)c.mesh.position.y+=.12;if(c.mesh)c.mesh.rotation.y=Math.atan2(q.t.x,q.t.z);}}
  function initVsc(){vscState.clear();for(const c of R.cars)if(!c.retired)vscState.set(c.id,{base:progress(c),allowed:0,actual:0,delta:0});}
  function deploy(type,reason,car,severity=.5){if((type==='SC'||type==='VSC')&&!physicalSCEnabled){addLocalYellow(car,reason,8,180);return'LOCAL YELLOW';}if(type==='SC'&&R.race.t<scCooldownUntil&&severity<.88)type='VSC';const rank={GREEN:0,VSC:1,SC:2,RED:3},now=R.race.t;if(rank[type]<rank[caution.type])return caution.type;const changed=type!==caution.type;caution.type=type;caution.reason=reason;caution.carId=car?.id??null;caution.severity=Math.max(caution.severity,severity);caution.startedAt=changed?now:caution.startedAt;caution.minUntil=Math.max(caution.minUntil,now+(type==='RED'?20:type==='SC'?18:12));if(changed){if(type==='RED'){caution.freeze=freezeCars();emit('RED_FLAG',null,{reason,physical:true});radio(null,`RED FLAG · ${reason}`,'CONTROL');}else if(type==='SC'){scCount++;caution.order=R.getStandings().map(c=>c.id);emit('SAFETY_CAR',null,{reason,physical:true});radio(null,`SAFETY CAR DEPLOYED · ${reason}`,'CONTROL');}else{initVsc();emit('VSC',null,{reason,physical:true});radio(null,`VSC DEPLOYED · ${reason}`,'CONTROL');}}return type;}
  function closeCaution(){if(caution.type==='GREEN')return;const old=caution.type;if(old==='SC')scCooldownUntil=R.race.t+70;caution.type='GREEN';caution.reason='';caution.carId=null;caution.severity=0;caution.minUntil=0;caution.freeze=null;caution.order=null;vscState.clear();emit(old==='RED'?'RED_RESTART':'GREEN_FLAG',null,{from:old,physical:true});radio(null,old==='RED'?'TRACK CLEAR · RESTART PROCEDURE':'GREEN FLAG · TRACK CLEAR','CONTROL');}
  function responsibilityFor(a,b,sev){if(!a||!b)return'RACING INCIDENT';const av=a.v||0,bv=b.v||0,closing=Math.abs(av-bv),lat=Math.abs((a.lane||0)-(b.lane||0));if(sev<.35||lat>((a.width||2)+(b.width||2))*.35)return'RACING INCIDENT';if(closing>12)return av>bv?`${a.name} under review for avoidable contact`:`${b.name} under review for avoidable contact`;return'INCIDENT UNDER REVIEW · no automatic fault assignment';}
  function reviewEvent(type,a,b,severity,cautionResult,data={}){const sa=Math.round((a?.v||0)*3.6),sb=Math.round((b?.v||0)*3.6),r={id:++reviewId,type,t:R.race.t,carA:a?.id??null,carB:b?.id??null,speedA:sa,speedB:sb,deltaV:Math.abs(sa-sb),severity,location:a?.s??b?.s??0,sector:sectorOf(a||b)+1,responsibility:type==='CONTACT'?responsibilityFor(a,b,severity):'RACING INCIDENT',caution:cautionResult,data};reviews.push(r);if(reviews.length>40)reviews.shift();emit('INCIDENT_REVIEW',a,{reviewId:r.id,type,caution:cautionResult,severity});return r;}
  function classifyContact(e){const a=R.cars[e.carId],b=R.cars[e.data?.otherId],sev=clamp(Number(e.data?.severity)||0,0,1);if(!a)return;const stoppedCars=[a,b].filter(c=>c&&(c.retired||c.v<5)),blocked=stoppedCars.filter(c=>Math.abs(c.lane||0)<3).length,recentSerious=reviews.filter(x=>R.race.t-x.t<5&&x.severity>.5).length,stopped=stoppedCars.length>0,onLine=[a,b].some(c=>c&&Math.abs(c.lane||0)<3),debris=Math.ceil(sev*8);if(sev>.34)W.spawnDebris?.(a,Math.max(2,debris));let result='LOCAL YELLOW';if(sev>=.94&&(blocked>=2||recentSerious>=2)){result=deploy('RED',`TRACK BLOCKED · CAR ${a.number}${b?` / CAR ${b.number}`:''}`,a,sev);for(const c of stoppedCars)startRecovery(c,'MAJOR CONTACT');}else if(sev>=.78||recentSerious>=1||(stopped&&onLine&&sev>.52)){result=deploy('SC',`CONTACT · CAR ${a.number}${b?` / CAR ${b.number}`:''}`,a,sev);for(const c of stoppedCars)startRecovery(c,'CONTACT');}else if(sev>=.52||stopped){result=deploy('VSC',`CONTACT · CAR ${a.number}`,a,sev);for(const c of stoppedCars)startRecovery(c,'CONTACT');}else addLocalYellow(a,'CONTACT',5+sev*5,130+sev*80);reviewEvent('CONTACT',a,b,sev,result,{debris,blocked});monitors.set(e.id,{carId:a.id,otherId:b?.id??null,expires:R.race.t+4,severity:sev});}
  function classifySpin(e){const c=R.cars[e.carId];if(!c)return;const sev=clamp(Number(e.data?.severity)||c.spinSeverity||.4,0,1),stopped=c.v<5,onLine=Math.abs(c.lane||0)<3.1;let result='LOCAL YELLOW';if(stopped&&onLine){result=deploy('VSC',`STOPPED CAR · ${c.name}`,c,sev);startRecovery(c,'SPIN');}else addLocalYellow(c,'SPIN',5+sev*3,140);reviewEvent('SPIN',c,null,sev,result);}
  function classifyRetirement(e){const c=R.cars[e.carId];if(!c)return;const onLine=Math.abs(c.lane||0)<3.2,result=deploy(onLine?'SC':'VSC',`STOPPED CAR · ${c.name}`,c,onLine?.82:.62);startRecovery(c,'RETIREMENT');reviewEvent('RETIREMENT',c,null,onLine?.82:.62,result);}
  function processEvents(){for(const e of R.events||[]){if(seen.has(e.id))continue;seen.add(e.id);if(e.type==='CONTACT')classifyContact(e);else if(e.type==='SPIN')classifySpin(e);else if(e.type==='RETIREMENT')classifyRetirement(e);}if(seen.size>500){const keep=new Set((R.events||[]).map(e=>e.id));for(const id of [...seen])if(!keep.has(id))seen.delete(id);}}
  function updateMonitors(){for(const [id,m] of [...monitors]){if(R.race.t>m.expires){monitors.delete(id);continue;}const cars=[R.cars[m.carId],R.cars[m.otherId]].filter(Boolean),stopped=cars.find(c=>c.retired||c.v<4);if(stopped&&!W.recoveryActive?.(stopped.id)&&m.severity>.45){startRecovery(stopped,'POST CONTACT');if(Math.abs(stopped.lane||0)<3)deploy(m.severity>.72?'SC':'VSC',`CAR STOPPED · ${stopped.name}`,stopped,m.severity);}}}
  function referenceVscSpeed(c){const load=clamp(W.braking?.(c.s)||0,0,1);return 50*(1-load*.46);}
  function applyLocalYellow(){for(let i=localYellows.length-1;i>=0;i--)if(localYellows[i].expires<=R.race.t)localYellows.splice(i,1);for(const c of R.cars){if(c.retired)continue;const local=localYellows.some(z=>trackDist(c.s,z.s)<z.radius);c.localYellow=local;if(local){c.v=Math.min(c.v,Math.max(18,referenceVscSpeed(c)*.82));c.drsActive=false;c.drsEligible=false;c.overtake=0;}}}
  function applyVsc(dt){for(const c of R.cars){if(c.retired||c.pitState==='STOP')continue;let s=vscState.get(c.id);if(!s){s={base:progress(c),allowed:0,actual:0,delta:0};vscState.set(c.id,s);}s.allowed+=referenceVscSpeed(c)*dt;s.actual=Math.max(0,progress(c)-s.base);s.delta=s.allowed-s.actual;if(s.delta<2){const cap=Math.max(12,referenceVscSpeed(c)*clamp(.82+s.delta*.06,.62,1));c.v=Math.min(c.v,cap);}c.vscDelta=s.delta;c.drsActive=false;c.drsEligible=false;c.overtake=0;}}
  function applySc(){const st=R.getStandings().filter(c=>!c.retired);for(let i=0;i<st.length;i++){const c=st[i];if(c.pitState==='STOP')continue;const pace=Math.max(18,32*(1-clamp(W.braking?.(c.s)||0,0,1)*.38));if(i===0){c.v=Math.min(c.v,pace);c.drsActive=false;c.drsEligible=false;c.overtake=0;continue;}const a=st[i-1],gap=Math.max(0,progress(a)-progress(c)),targetGap=20,correction=clamp((gap-targetGap)*.16,-6,7);c.v=Math.min(c.v,Math.max(10,pace+correction));c.drsActive=false;c.drsEligible=false;c.overtake=0;}}
  function applyCaution(dt){applyLocalYellow();if(caution.type==='RED')restoreFrozen();else if(caution.type==='VSC')applyVsc(dt);else if(caution.type==='SC')applySc();if(caution.type!=='GREEN'&&R.race.t>=caution.minUntil&&!activeRecovery()&&monitors.size===0)closeCaution();for(const t of W.recoveryHistory?.()||[]){if(t.done){const c=R.cars[t.carId];if(c?.retired&&!c.recovered){c.recovered=true;c.mesh.visible=false;emit('RECOVERY_COMPLETE',c,{reason:t.reason});}}}}
  function updateSectors(){for(const c of R.cars){const s=sector.get(c.id);if(!s||c.retired)continue;const cur=sectorOf(c);if(cur===s.current)continue;const old=s.current,elapsed=R.race.t-s.start;s.current=cur;s.start=R.race.t;if(elapsed<3||elapsed>120)continue;s.last[old]=elapsed;const green=effectiveFlag()==='GREEN'&&c.pitState==='NONE',oldPB=s.best[old],oldGB=globalBest[old];if(green){s.best[old]=Math.min(s.best[old],elapsed);globalBest[old]=Math.min(globalBest[old],elapsed);}s.deltaPersonal[old]=Number.isFinite(oldPB)?elapsed-oldPB:null;s.deltaOverall[old]=Number.isFinite(oldGB)?elapsed-oldGB:null;s.status[old]=green&&elapsed<=globalBest[old]+.0005?'PURPLE':green&&elapsed<=s.best[old]+.0005?'GREEN':'YELLOW';}}
  function updateCalibration(c){const x=calibration.get(c.id);if(!x||c.retired)return;if(Number.isFinite(c.lastLap)&&c.lastLap!==x.lastLapSeen){x.lastLapSeen=c.lastLap;if(effectiveFlag()==='GREEN'&&c.pitState==='NONE'&&c.lastLap>35&&c.lastLap<260){x.samples.push(c.lastLap);if(x.samples.length>3)x.samples.shift();if(x.samples.length===3){x.average=x.samples.reduce((a,b)=>a+b,0)/3;const mid=(x.target[0]+x.target[1])/2,err=clamp((x.average-mid)/mid,-.14,.14);x.factor=clamp(x.factor+err*.20,.9,1.1);}}}}
  function radarStrategy(c){if(c.retired||!W.env?.rainAt)return;const now=W.env.rainAt(c.s,0),m1=W.env.rainAt(c.s,60),m3=W.env.rainAt(c.s,180);c.radarForecast={now,in60:m1,in180:m3};const wet=W.env.wetness||0,needWet=!['WET','INTERMEDIATE'].includes(c.compound)&&(now>.48||(W.env.rain>.16&&m1>.62)),needDry=['WET','INTERMEDIATE'].includes(c.compound)&&now<.12&&m1<.18&&wet<.24;if((needWet||needDry)&&c.pitState==='NONE'&&c.lap>0&&c.s>total*.72)c.pitState='ENTRY';}
  function update(dt){const step=clamp(Number(dt)||.016,.001,.05);applyCaution(step);baseUpdate(step);processEvents();updateMonitors();applyCaution(step);updateSectors();for(const c of R.cars){updateCalibration(c);radarStrategy(c);}}
  return new Proxy(R,{get(target,prop){if(prop==='update')return update;if(prop==='flag')return effectiveFlag();if(prop==='physicalCaution')return{type:effectiveFlag(),reason:caution.reason,carId:caution.carId,severity:caution.severity,scCount,cooldownRemaining:Math.max(0,scCooldownUntil-R.race.t),localYellows:[...localYellows],recoveries:W.activeRecoveries?.()||[]};if(prop==='raceControl')return{owner:'runtime-race-control-v2',caution:{...caution,freeze:undefined},scCount,cooldownRemaining:Math.max(0,scCooldownUntil-R.race.t),vsc:[...vscState].map(([carId,s])=>({carId,...s}))};if(prop==='incidentReviews')return reviews;if(prop==='sectorTimingFor')return id=>sector.get(Number(id))||null;if(prop==='paceCalibrationFor')return id=>calibration.get(Number(id))||null;return Reflect.get(target,prop,target);}});
}
