export function createRace(W,statusEl){
 const T=W.THREE,{clamp,wrap,total,sample,braking}=W;
 const colors=[0xf23b35,0x2f7fe8,0xffce32,0xf3f3f3,0x18c982,0x9d62ef,0xf57c22,0x1eb9c5,0xf24f9a,0xb7bdc6];
 const types=['formula','gt','proto'];
 const compounds={SOFT:{grip:1.035,wear:1.38,color:'#e53935'},MEDIUM:{grip:1,wear:1,color:'#f2d230'},HARD:{grip:.975,wear:.72,color:'#eeeeee'},INTERMEDIATE:{grip:.955,wear:1.05,color:'#2ecc71'},WET:{grip:.91,wear:.58,color:'#3f7de8'}};
 const driverNames=['SATO','MORI','KAI','REN','TAKEDA','ITO','NOVA','AKI','KODA','RUI','JIN','MAYA','LEO','YUKI','HINA','AOI','RYO','SENA','NICO','REI'];
 const cars=[],laneLimit=3.9,events=[],history=[];
 let historyClock=0,fastestLap=Infinity,replay=null,flag='GREEN',flagTimer=0,safetyReason='',raceFinished=false;
 const race={t:0,green:4,lapsTarget:6,flag:'GREEN'};
 const externalLaneAuthority=()=>W.runtimeRacecraftAuthority==='runtime-racecraft-v2';
 function personality(i){return{aggression:.48+((i*37)%49)/100,racecraft:.76+((i*17)%21)/100,tireCare:.72+((i*29)%25)/100,wetSkill:.70+((i*23)%28)/100,errorRate:.00045+((i*13)%9)*.00008};}
 for(let i=0;i<20;i++){const type=types[i%3],mesh=W.makeCar(colors[i%colors.length],type),d=mesh.userData.dims,p=personality(i);W.scene.add(mesh);const row=Math.floor(i/2),col=i%2,lane=(col?-1:1)*2.55+(row%2?.14:-.14),skill=.94+((i*7)%13)*.006;const compound=i%4===0?'SOFT':i%4===1?'HARD':'MEDIUM';cars.push({id:i,number:i+1,name:driverNames[i],mesh,type,length:d.length,width:d.width,s:wrap(-row*12.4,total),lane,laneTarget:lane,v:0,prevV:0,baseMax:(type==='formula'?79:type==='gt'?73:76)*skill,max:0,accel:(type==='formula'?6.9:type==='gt'?6.1:6.5)+skill*.7,brake:16.5,lap:0,overtake:0,avoid:0,reaction:.10+Math.random()*.55,launch:1+Math.random()*.09,wheelSpin:0,brakeVisual:0,driver:p,compound,wear:0,fuel:1,pits:0,pitTimer:0,pitState:'NONE',lastLapStart:0,lastLap:null,bestLap:Infinity,position:i+1,prevPosition:i+1,incident:0,damage:0,retired:false,lastOvertakeEvent:-99});}
 const gap=(a,b)=>wrap(b.s-a.s,total);
 function rankCars(){const sorted=[...cars].filter(c=>!c.retired).sort((a,b)=>(b.lap*total+b.s)-(a.lap*total+a.s));sorted.forEach((c,i)=>c.position=i+1);return sorted;}
 function emit(type,car,data={}){events.push({id:Math.random().toString(36).slice(2),type,t:race.t,carId:car?.id??null,data});if(events.length>80)events.shift();}
 function ahead(c,idx){let car=null,g=1e9;for(let j=0;j<cars.length;j++)if(j!==idx&&!cars[j].retired){const q=gap(c,cars[j]);if(q<g){g=q;car=cars[j];}}return{car,g};}
 function laneClear(idx,target,aheadDist=44,behindDist=20){const me=cars[idx];for(let j=0;j<cars.length;j++)if(j!==idx&&!cars[j].retired){const o=cars[j],ga=gap(me,o),gb=gap(o,me),lat=Math.abs(o.lane-target),min=(me.width+o.width)*.42+.45;if((ga<aheadDist||gb<behindDist)&&lat<min)return false;}return true;}
 function laneScore(idx,target){const me=cars[idx];let score=0;for(let j=0;j<cars.length;j++)if(j!==idx&&!cars[j].retired){const o=cars[j],ga=gap(me,o),gb=gap(o,me),lat=Math.abs(o.lane-target);if(ga<60)score+=Math.min(24,ga)*.26+lat*1.9;if(gb<24)score+=Math.min(14,gb)*.18+lat*1.5;}return score-Math.abs(target)*.08;}
 function chooseLane(idx){const c=[-3.25,3.25].filter(x=>laneClear(idx,x));if(!c.length)return null;c.sort((a,b)=>laneScore(idx,b)-laneScore(idx,a));return c[0];}
 function pose(c){const q=sample(c.s,c.lane),now=Number(race.t)||0,last=Number(c._lastPoseAt),poseDt=Number.isFinite(last)?clamp(now-last,0,.05):0;c._lastPoseAt=now;c.mesh.visible=!c.retired;c.mesh.position.copy(q.p);c.mesh.position.y+=.12;c.mesh.rotation.y=Math.atan2(q.t.x,q.t.z);const vis=c.mesh.userData.visual,visualAlpha=1-Math.pow(1-.22,poseDt*60);if(vis)vis.rotation.x=T.MathUtils.lerp(vis.rotation.x,c.brakeVisual*.045,visualAlpha);c.wheelSpin+=c.v*1.08*poseDt;for(const w of c.mesh.userData.wheels||[])w.rotation.x=c.wheelSpin;for(const m of c.mesh.userData.brakeMats||[])m.emissiveIntensity=.05+c.brakeVisual*2.8;}
 function separate(){if(W.runtimeTrajectoryControl)return;for(let i=0;i<cars.length;i++)for(let j=i+1;j<cars.length;j++){const a=cars[i],b=cars[j];if(a.retired||b.retired)continue;const ga=gap(a,b),gb=gap(b,a),f=ga<gb?ga:-gb,ad=Math.abs(f),lat=b.lane-a.lane,minL=(a.length+b.length)*.48+.75,minW=(a.width+b.width)*.31;if(ad<minL&&Math.abs(lat)<minW){const dir=(lat||((i+j)%2?1:-1))>0?1:-1,p=(minW-Math.abs(lat)+.05)*.38;a.lane=clamp(a.lane-dir*p,-laneLimit,laneLimit);b.lane=clamp(b.lane+dir*p,-laneLimit,laneLimit);if(f>0){a.v=Math.min(a.v,b.v*.97);a.s=wrap(a.s-(minL-ad)*.28,total);}else{b.v=Math.min(b.v,a.v*.97);b.s=wrap(b.s-(minL-ad)*.28,total);}}}}
 function snapshot(){return{t:race.t,cars:cars.map(c=>({s:c.s,lane:c.lane,v:c.v,lap:c.lap,wear:c.wear,compound:c.compound,retired:c.retired}))};}
 function storeHistory(dt){historyClock+=dt;if(historyClock<.11)return;historyClock=0;history.push(snapshot());while(history.length&&race.t-history[0].t>8.5)history.shift();}
 function applySnapshot(snap){snap.cars.forEach((x,i)=>{const c=cars[i];c.s=x.s;c.lane=x.lane;c.v=x.v;c.lap=x.lap;c.wear=x.wear;c.compound=x.compound;c.retired=x.retired;pose(c);});}
 function startReplay(seconds=5){if(replay||history.length<8)return false;const end=history.length-1,start=Math.max(0,end-Math.floor(seconds/.11));const frames=history.slice(start,end+1);replay={frames,index:0,acc:0,restore:snapshot(),speed:.55};emit('REPLAY',null,{seconds});return true;}
 function updateReplay(dt){if(!replay)return false;replay.acc+=dt*replay.speed;while(replay.acc>=.11&&replay.index<replay.frames.length-1){replay.acc-=.11;replay.index++;}applySnapshot(replay.frames[replay.index]);if(replay.index>=replay.frames.length-1){const r=replay.restore;replay=null;applySnapshot(r);}return true;}
 function setFlag(next,duration,reason=''){flag=next;race.flag=next;flagTimer=duration;safetyReason=reason;emit(next==='SC'?'SAFETY_CAR':'YELLOW',null,{reason});}
 function maybeIncident(c,dt,load){if(c.incident>0){c.incident-=dt;return;}if(race.t<race.green+8||flag!=='GREEN')return;const wet=W.env?.wetness||0;const risk=c.driver.errorRate*(1+load*2.2+wet*(1.25-c.driver.wetSkill)*5);if(Math.random()<risk*dt){c.incident=3.5;c.laneTarget=clamp((Math.random()<.5?-1:1)*3.75,-laneLimit,laneLimit);c.v*=.72;c.damage=clamp(c.damage+.08+Math.random()*.12,0,.8);emit('INCIDENT',c,{damage:c.damage});if(Math.random()<.24||c.damage>.45)setFlag('SC',12,`${c.name} incident`);else setFlag('YELLOW',6,`${c.name} off track`);}}
 function choosePit(c){const rain=W.env?.rain||0,wet=W.env?.wetness||0;if(c.pitState!=='NONE'||c.retired)return false;const needWet=wet>.48&&c.compound!=='WET';const needDry=wet<.18&&c.compound==='WET';const worn=c.wear>(c.compound==='SOFT'?.68:c.compound==='MEDIUM'?.76:.82);if((needWet||needDry||worn)&&c.lap>0&&c.s>total*.78){c.pitState='ENTRY';c.pitTimer=0;emit('PIT_CALL',c,{wear:c.wear,compound:c.compound});return true;}return false;}
 function updatePit(c,dt){if(c.pitState==='NONE')return false;if(c.pitState==='ENTRY'){c.laneTarget=3.7;if(c.s>total*.92||c.s<total*.08)c.max=Math.min(c.max,24);if(c.s<total*.06&&c.lap>0){c.pitState='STOP';c.pitTimer=2.4+(1-c.driver.racecraft)*1.4;c.v=0;emit('PIT_STOP',c,{stop:c.pitTimer});}return false;}if(c.pitState==='STOP'){c.v=0;c.pitTimer-=dt;if(c.pitTimer<=0){const wet=W.env?.wetness||0;c.compound=wet>.38?'WET':(c.driver.tireCare>.84?'SOFT':'MEDIUM');c.wear=0;c.pits++;c.pitState='EXIT';emit('PIT_EXIT',c,{compound:c.compound});}return true;}if(c.pitState==='EXIT'){c.laneTarget=3.5;if(c.s>total*.08){c.pitState='NONE';c.laneTarget=0;}return false;}return false;}
 function tyreFactor(c){const spec=compounds[c.compound]||compounds.MEDIUM,wet=W.env?.wetness||0;let grip=spec.grip*(1-c.wear*.23);if(c.compound==='INTERMEDIATE')grip*=clamp(.88+wet*.23,.84,1.06);else if(c.compound==='WET')grip*=wet>.35?1.08:.82;else grip*=1-wet*(.24+(1-c.driver.wetSkill)*.26);return clamp(grip,.62,1.07);}
 cars.forEach(pose);
 function update(dt){
  if(updateReplay(dt))return;race.t+=dt;if(flagTimer>0){flagTimer-=dt;if(flagTimer<=0){flag='GREEN';race.flag='GREEN';emit('GREEN_FLAG',null,{reason:safetyReason});}}
  if(race.t<race.green){statusEl.textContent='LIGHTS '+Math.max(1,Math.ceil(race.green-race.t));cars.forEach(pose);storeHistory(dt);return;}
  statusEl.textContent=flag==='GREEN'?(race.t<race.green+.6?'GREEN':'RUNNING'):flag;const before=rankCars().map(c=>c.id);
  for(let i=0;i<cars.length;i++){
   const c=cars[i];if(c.retired)continue;const load=braking(c.s);maybeIncident(c,dt,load);choosePit(c);const spec=compounds[c.compound]||compounds.MEDIUM,grip=tyreFactor(c),personalitySpeed=.965+c.driver.racecraft*.05;c.max=c.baseMax*grip*personalitySpeed*(1-c.damage*.25);if(flag==='YELLOW')c.max=Math.min(c.max,42);if(flag==='SC')c.max=Math.min(c.max,30);if(updatePit(c,dt)){pose(c);continue;}
   let target=Math.max(18,c.max*(1-.70*load));if(race.t<race.green+c.reaction)target=0;else if(race.t<race.green+4.5)target=Math.max(target,c.max*.82*c.launch);const f=ahead(c,i);
   if(f.car){const lat=Math.abs(f.car.lane-c.lane),overlap=lat<(c.width+f.car.width)*.43+.35,closing=Math.max(0,c.v-f.car.v),safe=(c.length+f.car.length)*.55+4.5,ttc=closing>.5?(f.g-safe)/closing:99;if(flag==='GREEN'&&overlap&&f.g<120&&f.g>32)target*=1.02+c.driver.aggression*.025;if(overlap&&(f.g<42||ttc<2.5)){const opt=(!externalLaneAuthority()&&flag==='GREEN'&&c.avoid<=0&&load<.62)?chooseLane(i):null;if(opt!==null){c.laneTarget=opt;c.avoid=1.7+(1-c.driver.racecraft);c.overtake=2.8;}const margin=clamp((f.g-safe)/20,0,1);target=Math.min(target,f.car.v+margin*6);if(ttc<1.25||f.g<safe+4)target=Math.min(target,f.car.v*.97);}}
   if(c.avoid>0)c.avoid-=dt;if(c.overtake>0)c.overtake-=dt;if(!externalLaneAuthority()){if(flag!=='GREEN')c.laneTarget*=.92;else if(load>.46&&c.avoid<=0)c.laneTarget*=.90;else if(c.avoid<=0)c.laneTarget*=.997;}c.laneTarget=clamp(c.laneTarget,-laneLimit,laneLimit);
   const dv=target-c.v,rate=dv>0?c.accel:c.brake;c.prevV=c.v;c.v+=clamp(dv,-rate*dt,rate*dt);const dec=Math.max(0,(c.prevV-c.v)/Math.max(dt,.001));c.brakeVisual=T.MathUtils.lerp(c.brakeVisual,clamp(dec/12,0,1),1-Math.exp(-8*dt));
   if(!W.runtimeTrajectoryControl)c.lane=T.MathUtils.lerp(c.lane,c.laneTarget,1-Math.exp(-2.1*dt));
   c.wear=clamp(c.wear+dt*(.00052+load*.00115)*spec.wear*(1.18-c.driver.tireCare),0,1);c.fuel=clamp(c.fuel-dt*.00022,0,1);const old=c.s;c.s=wrap(c.s+c.v*dt,total);if(c.s<old-total*.5){c.lap++;const lapTime=race.t-c.lastLapStart;c.lastLap=lapTime;c.lastLapStart=race.t;c.bestLap=Math.min(c.bestLap,lapTime);if(lapTime<fastestLap&&c.lap>1){fastestLap=lapTime;emit('FASTEST_LAP',c,{lapTime});}if(c.lap>=race.lapsTarget&&!raceFinished){raceFinished=true;emit('FINISH',c,{ });}}
  }
  separate();cars.forEach(pose);const after=rankCars();after.forEach((c,i)=>{const old=before.indexOf(c.id);if(old>=0&&i<old&&race.t>race.green+6&&race.t-c.lastOvertakeEvent>2){emit('OVERTAKE',c,{from:old+1,to:i+1});c.lastOvertakeEvent=race.t;}c.prevPosition=c.position;});storeHistory(dt);
 }
 function getStandings(){return rankCars();}
 return{cars,race,events,history,compounds,update,leader:()=>getStandings()[0]?.id??0,getStandings,startReplay,get replay(){return replay},get flag(){return flag},get fastestLap(){return fastestLap}};
}
