export function createSafetyCar(W,R){
  const T=W.THREE,mesh=W.makeCar(0x111417,'supercar');mesh.visible=false;W.scene.add(mesh);const visual=mesh.userData.visual||mesh,d=mesh.userData.dims||{length:6.5,width:3};
  const black=new T.MeshStandardMaterial({color:0x080a0c,roughness:.24,metalness:.48}),graphite=new T.MeshStandardMaterial({color:0x191d21,roughness:.28,metalness:.42}),white=new T.MeshStandardMaterial({color:0xf1f3f4,roughness:.36,metalness:.10}),red=new T.MeshStandardMaterial({color:0xb51018,emissive:0x430000,emissiveIntensity:.35,roughness:.28,metalness:.22}),amberA=new T.MeshStandardMaterial({color:0x7a3900,emissive:0xffa000,emissiveIntensity:.25,roughness:.20}),amberB=amberA.clone(),green=new T.MeshStandardMaterial({color:0x005d28,emissive:0x2dff79,emissiveIntensity:.35,roughness:.18});
  const add=(geo,mat,x=0,y=0,z=0,rx=0,ry=0,rz=0)=>{const m=new T.Mesh(geo,mat);m.position.set(x,y,z);m.rotation.set(rx,ry,rz);m.castShadow=true;visual.add(m);return m;};add(new T.BoxGeometry(d.width*.74,.055,d.length*.58),graphite,0,.86,-.02);for(const s of[-1,1]){add(new T.BoxGeometry(d.width*.11,.060,d.length*.72),red,s*d.width*.30,.89,.00,0,s*.08,0);add(new T.BoxGeometry(d.width*.055,.062,d.length*.48),white,s*d.width*.20,.91,.02,0,s*.05,0);}add(new T.BoxGeometry(d.width*.60,.060,.20),red,0,.92,d.length*.39);add(new T.BoxGeometry(d.width*.58,.060,.18),red,0,.92,-d.length*.39);
  const bar=new T.Group();bar.position.set(0,1.78,-.06);visual.add(bar);bar.add(new T.Mesh(new T.BoxGeometry(1.78,.10,.32),black));const lights=[];for(let i=0;i<8;i++){const mat=i%2?amberA:amberB,l=new T.Mesh(new T.BoxGeometry(.18,.16,.27),mat);l.position.set((i-3.5)*.215,.11,0);bar.add(l);lights.push(l);}const frontLed=[];for(let i=0;i<6;i++){const l=new T.Mesh(new T.BoxGeometry(.19,.055,.035),green);l.position.set((i-2.5)*.22,1.38,d.length*.45);visual.add(l);frontLed.push(l);}
  let time=0,scS=0,active=false;const wrap=s=>((s%(W.total||1))+(W.total||1))%(W.total||1),forward=(a,b)=>((b-a)%(W.total||1)+(W.total||1))%(W.total||1);
  function update(dt=.016){const step=Math.min(.05,Math.max(0,dt));time+=step;if(R.flag!=='SC'){mesh.visible=false;active=false;return;}const leader=R.getStandings()[0];if(!leader){mesh.visible=false;active=false;return;}if(!active){scS=wrap((leader.s||0)+42);active=true;}const gap=forward(leader.s||0,scS),load=Math.max(0,Math.min(1,Number(W.braking?.(scS))||0)),basePace=Math.max(18,32*(1-load*.38)),correction=gap>65?-6:gap<24?4:0,pace=Math.max(14,basePace+correction);scS=wrap(scS+pace*step);const q=W.sample(scS,0);mesh.visible=true;mesh.position.copy(q.p);mesh.position.y+=.12;mesh.rotation.y=Math.atan2(q.t.x,q.t.z);const a=Math.sin(time*17)>0,b=Math.sin(time*17+Math.PI)>0;amberA.emissiveIntensity=a?8:.18;amberB.emissiveIntensity=b?8:.18;green.emissiveIntensity=(Math.sin(time*10)>.45)?3:.28;for(const l of lights)l.scale.y=.86+(l.material.emissiveIntensity>1?.34:0);for(const l of frontLed)l.scale.x=.92+(green.emissiveIntensity>1?.18:0);mesh.userData.safetyCar={s:scS,pace,gapToLeader:gap};}
  return{update,mesh,get state(){return{active,s:scS,pace:mesh.userData.safetyCar?.pace||0,gapToLeader:mesh.userData.safetyCar?.gapToLeader||0};}};
}
