export function attachControlUI(base,W,R,D,settings,saveSettings){
  const drawer=document.getElementById('v16Drawer'),tabs=document.getElementById('v16Tabs');
  let focus=0,acc=0,ctrlOpen=false;
  const style=document.createElement('style');style.textContent=`#v24Info{position:fixed;z-index:72;left:12px;bottom:max(12px,env(safe-area-inset-bottom));max-width:82vw;padding:6px 9px;border-radius:8px;background:#07121bdc;border:1px solid #ffffff20;font:800 9px/1.35 -apple-system,sans-serif;pointer-events:none;opacity:.92}#v24Ctrl{display:none;position:absolute;z-index:7;left:0;right:0;top:45px;bottom:0;overflow:auto;padding:8px;background:#07121bf8;font-size:10px;line-height:1.4}#v24Ctrl.open{display:block}.v24wheel{display:grid;grid-template-columns:34px repeat(4,1fr);gap:3px;text-align:center}.v24wheel>*{padding:3px;background:#ffffff0a;border-radius:4px}.v24perf{margin-top:8px;padding-top:7px;border-top:1px solid #ffffff20}`;document.head.appendChild(style);
  const info=document.createElement('div');info.id='v24Info';document.body.appendChild(info);
  if(!drawer||!tabs)return base;
  const ctrlTab=document.createElement('button');ctrlTab.textContent='CTRL';ctrlTab.id='v24CtrlTab';const setTab=tabs.querySelector('[data-tab="set"]');tabs.insertBefore(ctrlTab,setTab||null);
  const ctrl=document.createElement('div');ctrl.id='v24Ctrl';drawer.appendChild(ctrl);
  const pct=x=>`${Math.round((x||0)*100)}%`;

  function performanceFields(){return `<div id="v24PerfSettings" class="v24perf"><b>PERFORMANCE</b><br><span class="muted">変更は再起動後に反映</span><div class="setting"><span>Preset</span><select id="setPerfMode"><option>AUTO</option><option>QUALITY</option><option>BALANCED</option><option>COOL</option><option>BATTERY</option></select></div><div class="setting"><span>FPS cap</span><select id="setFpsCap"><option>AUTO</option><option>60</option><option>45</option><option>30</option></select></div><div class="setting"><span>Render scale</span><select id="setRenderScale"><option value="1.15">115%</option><option value="1">100%</option><option value="0.9">90%</option><option value="0.8">80%</option><option value="0.7">70%</option></select></div><div class="setting"><span>Shadows</span><select id="setShadows"><option value="1">On</option><option value="0">Off</option></select></div><div class="setting"><span>Auto quality</span><select id="setAutoQuality"><option value="1">On</option><option value="0">Off</option></select></div></div>`;}
  function enhanceSettings(){const apply=document.getElementById('applySettings');if(!apply||document.getElementById('v24PerfSettings'))return;apply.insertAdjacentHTML('beforebegin',performanceFields());const v=(id,val)=>{const e=document.getElementById(id);if(e)e.value=String(val);};v('setPerfMode',settings.perfMode||'AUTO');v('setFpsCap',settings.fpsCap??'AUTO');v('setRenderScale',settings.renderScale??1);v('setShadows',settings.shadows===false?0:1);v('setAutoQuality',settings.autoQuality===false?0:1);}
  drawer.addEventListener('click',e=>{if(e.target?.id==='applySettings'){const get=id=>document.getElementById(id)?.value;settings.perfMode=get('setPerfMode')||settings.perfMode||'AUTO';settings.fpsCap=get('setFpsCap')||settings.fpsCap||'AUTO';settings.renderScale=Number(get('setRenderScale')||settings.renderScale||1);settings.shadows=get('setShadows')!=='0';settings.autoQuality=get('setAutoQuality')!=='0';saveSettings(settings);}},true);
  const obs=new MutationObserver(enhanceSettings);obs.observe(drawer,{subtree:true,childList:true});

  function ctrlHTML(){const c=R.cars[focus]||R.getStandings()[0],cases=[...(R.stewardCases||[])].reverse().slice(0,8),t=R.trackEvolution||{};if(!c)return'';const ds=c.driverState||{},st=c.strategy||{},ws=c.wheelState||[];let h=`<div class="v16section"><b>RACE CONTROL / CAR STATE</b><br><span class="tag">${c.energyMode||'BALANCED'}</span><span class="tag">ERS ${pct(c.ers)}</span><span class="tag">SLIP ${pct(c.slipstream)}</span><span class="tag ${c.dirtyAir>.2?'warn':''}">DIRTY ${pct(c.dirtyAir)}</span></div><div class="v16section"><b>STRATEGY</b><br>${st.reason||'BASELINE'} · ${st.window||'--'}<br><span class="tag">UNDER ${pct(st.undercut)}</span><span class="tag">OVER ${pct(st.overcut)}</span>${st.freeStop?'<span class="tag good">CHEAP STOP</span>':''}</div><div class="v16section"><b>DRIVER STATE</b><br><span class="tag">CONF ${pct(ds.confidence)}</span><span class="tag">PRESS ${pct(ds.pressure)}</span><span class="tag">MORALE ${pct(ds.morale)}</span><span class="tag">FAT ${pct(ds.fatigue)}</span></div><div class="v16section"><b>TRACK</b><br>RUBBER ${pct(t.rubber)} · MARBLES ${pct(t.marbles)} · DRY LINE ${pct(t.dryLine)}</div>`;
    h+=`<div class="v16section"><b>4-WHEEL STATE</b><div class="v24wheel"><b></b>${ws.map(w=>`<b>${w.name}</b>`).join('')}<span>TEMP</span>${ws.map(w=>`<span>${Math.round(w.temp)}°</span>`).join('')}<span>WEAR</span>${ws.map(w=>`<span>${Math.round(w.wear*100)}%</span>`).join('')}<span>BRK</span>${ws.map(w=>`<span>${Math.round(w.brake)}°</span>`).join('')}<span>STATE</span>${ws.map(w=>`<span>${w.puncture?'PUNCT':w.nutIssue?'NUT':w.flat>.15?'FLAT':'OK'}</span>`).join('')}</div></div>`;
    h+='<div class="v16section"><b>STEWARDS</b>';if(!cases.length)h+='<br><span class="muted">No active/recent cases.</span>';for(const x of cases){const car=x.carId!=null?R.cars[x.carId]:null;h+=`<div class="v16section"><b>#${x.id} ${x.type.replaceAll('_',' ')}</b><br>${car?.name||'RACE'} · ${x.status}</div>`;}return h+'</div>';}
  function renderCtrl(){if(ctrlOpen)ctrl.innerHTML=ctrlHTML();}
  ctrlTab.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();ctrlOpen=true;ctrl.classList.add('open');tabs.querySelectorAll('button').forEach(b=>b.classList.toggle('on',b===ctrlTab));renderCtrl();},{capture:true});
  tabs.addEventListener('click',e=>{if(e.target===ctrlTab)return;ctrlOpen=false;ctrl.classList.remove('open');},{capture:true});

  function enhanceTelem(){const p=document.getElementById('v19Telem'),c=R.cars[focus];if(!p?.classList.contains('open')||!c||document.getElementById('v24WheelTelem'))return;const ws=c.wheelState||[];const d=document.createElement('div');d.id='v24WheelTelem';d.className='v16section';d.innerHTML=`<b>4-WHEEL LIVE</b><div class="v24wheel"><b></b>${ws.map(w=>`<b>${w.name}</b>`).join('')}<span>TEMP</span>${ws.map(w=>`<span>${Math.round(w.temp)}°</span>`).join('')}<span>WEAR</span>${ws.map(w=>`<span>${Math.round(w.wear*100)}%</span>`).join('')}</div>`;p.appendChild(d);}
  function progress(c){return c?._v8Progress??((c?.lap||0)*W.total+(c?.s||0));}
  function updateInfo(){const c=R.cars[D.focus]||R.getStandings()[0];if(!c){info.style.display='none';return;}info.style.display='block';const a=R.getStandings()[Math.max(0,(c.position||1)-2)],gap=a&&a!==c?Math.abs((progress(a)-progress(c))/Math.max(1,c.v)).toFixed(1):'--',st=c.strategy||{};info.textContent=`${c.battleState&&c.battleState!=='CLEAR'?'BATTLE':'LIVE'} · P${c.position} ${c.name} · ${String(c.type||'car').toUpperCase()} · GAP ${gap}s · ${c.compound} ${Math.round((c.wear||0)*100)}% · ${c.energyMode||'BALANCED'} · ${st.reason||'BASELINE'}`;}
  const oldUpdate=base.update;
  return new Proxy(base,{get(target,prop){if(prop==='update')return(dt,id)=>{focus=Number(id)||0;const setOpen=drawer.classList.contains('open')&&!!tabs.querySelector('[data-tab="set"]')?.classList.contains('on');if(!setOpen)oldUpdate(dt,id);acc+=dt;if(acc>=.5){acc=0;enhanceSettings();renderCtrl();enhanceTelem();updateInfo();}};return Reflect.get(target,prop,target);}});
}
