import {createUI as createCoreUI} from './ui-core.js';
import {attachRadioUI} from './ui-radio.js';
import {attachTelemetryUI} from './ui-telemetry.js';
import {attachControlUI} from './ui-control.js';
import {readAudioSettings} from './config.js';

export function createUI(W,R,D,E,C,A,settings,saveSettings){
  let base=createCoreUI(W,R,D,E,C,A,settings,saveSettings);
  base=attachRadioUI(base,A);
  base=attachTelemetryUI(base,W,R);
  base=attachControlUI(base,W,R,D,settings,saveSettings);
  const drawer=document.getElementById('v16Drawer'),tabs=document.getElementById('v16Tabs');
  let focus=0,acc=0,radarOpen=false,deltaOpen=false;
  if(!drawer||!tabs)return base;

  const style=document.createElement('style');style.textContent=`#v26Radar,#v26Delta{display:none;position:absolute;z-index:9;left:0;right:0;top:45px;bottom:0;overflow:auto;padding:8px;background:#07121bfa;font-size:10px;line-height:1.4}#v26Radar.open,#v26Delta.open{display:block}#v26RadarCanvas{width:100%;height:220px;background:#071018;border:1px solid #ffffff18;border-radius:10px}.v26forecast{display:grid;grid-template-columns:50px 1fr 45px;gap:5px;align-items:center;padding:5px 0;border-top:1px solid #ffffff10}.v26bar{height:8px;border-radius:6px;background:#ffffff10;overflow:hidden}.v26fill{height:100%;background:#54a9ff}.v26delta{display:grid;grid-template-columns:24px 1fr repeat(3,58px);gap:4px;align-items:center;padding:5px 2px;border-top:1px solid #ffffff12}.purple{color:#df6cff}.sectorGreen{color:#62ff8a}.sectorYellow{color:#ffd85a}.v26recovery{height:6px;background:#ffffff12;border-radius:5px;overflow:hidden;margin-top:4px}.v26recovery>i{display:block;height:100%;background:#ffcf55}`;document.head.appendChild(style);
  const makeTab=(id,text)=>{const b=document.createElement('button');b.id=id;b.textContent=text;const set=tabs.querySelector('[data-tab="set"]');tabs.insertBefore(b,set||null);return b;};
  const radarTab=makeTab('v26RadarTab','RDR'),deltaTab=makeTab('v26DeltaTab','DELTA');
  const radar=document.createElement('div');radar.id='v26Radar';drawer.appendChild(radar);const delta=document.createElement('div');delta.id='v26Delta';drawer.appendChild(delta);
  const track=[];for(let i=0;i<180;i++){const p=W.sample(W.total*i/180).p;track.push([p.x,p.z]);}const xs=track.map(p=>p[0]),zs=track.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minZ=Math.min(...zs),maxZ=Math.max(...zs);
  const fmt=t=>!Number.isFinite(t)?'--':`${Math.floor(t/60)}:${(t%60).toFixed(1).padStart(4,'0')}`;
  const signed=x=>x==null?'--':`${x>=0?'+':''}${x.toFixed(3)}`;
  function hide(){radarOpen=deltaOpen=false;radar.classList.remove('open');delta.classList.remove('open');}
  function activate(which){hide();document.getElementById('v19Telem')?.classList.remove('open');document.getElementById('v24Ctrl')?.classList.remove('open');drawer.classList.remove('v19telem');if(which==='radar'){radarOpen=true;radar.classList.add('open');}else{deltaOpen=true;delta.classList.add('open');}tabs.querySelectorAll('button').forEach(b=>b.classList.toggle('on',b===(which==='radar'?radarTab:deltaTab)));}
  radarTab.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();activate('radar');renderRadar();},{capture:true});deltaTab.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();activate('delta');renderDelta();},{capture:true});
  tabs.addEventListener('click',e=>{if(e.target===radarTab||e.target===deltaTab)return;hide();},{capture:true});

  function rainColor(v){if(v>.72)return'#9b5cff';if(v>.48)return'#397dff';if(v>.22)return'#55c7ff';if(v>.06)return'#8ce6ff';return'#36434b';}
  function drawRadar(){const cv=radar.querySelector('#v26RadarCanvas'),rd=E.radar;if(!cv||!rd?.segments?.length)return;const dpr=Math.min(devicePixelRatio||1,1.5),w=Math.max(280,cv.clientWidth||340),h=220;cv.width=w*dpr;cv.height=h*dpr;const g=cv.getContext('2d');g.setTransform(dpr,0,0,dpr,0,0);g.clearRect(0,0,w,h);const pad=18,scale=Math.min((w-pad*2)/(maxX-minX),(h-pad*2)/(maxZ-minZ)),mp=(x,z)=>[pad+(x-minX)*scale,h-pad-(z-minZ)*scale];g.lineCap='round';g.lineJoin='round';for(let i=0;i<track.length;i++){const j=(i+1)%track.length,[x1,y1]=mp(...track[i]),[x2,y2]=mp(...track[j]),ri=Math.floor(i/track.length*rd.segments.length)%rd.segments.length;g.strokeStyle=rainColor(rd.segments[ri]);g.lineWidth=8;g.beginPath();g.moveTo(x1,y1);g.lineTo(x2,y2);g.stroke();}const c=R.cars[focus]||R.getStandings()[0];if(c){const [x,y]=mp(c.mesh.position.x,c.mesh.position.z);g.fillStyle='#fff';g.beginPath();g.arc(x,y,5,0,Math.PI*2);g.fill();}}
  function renderRadar(){if(!radarOpen)return;const rd=E.radar||{horizons:[]},rows=rd.horizons||[];radar.innerHTML=`<div class="v16section"><b>WEATHER RADAR</b><br><span class="muted">Track rain cells · forecast drives strategy AI</span></div><canvas id="v26RadarCanvas"></canvas><div class="v16section"><b>FORECAST</b>${rows.map(r=>{const avg=(r.values||[]).reduce((a,b)=>a+b,0)/Math.max(1,r.values?.length||1),peak=Math.max(0,...(r.values||[0]));const label=r.seconds===0?'NOW':`+${Math.round(r.seconds/60)}m`;return`<div class="v26forecast"><b>${label}</b><div class="v26bar"><div class="v26fill" style="width:${Math.round(peak*100)}%"></div></div><span>${Math.round(avg*100)}%</span></div>`;}).join('')}</div>`;drawRadar();}
  function cls(st){return st==='PURPLE'?'purple':st==='GREEN'?'sectorGreen':'sectorYellow';}
  function renderDelta(){if(!deltaOpen)return;const st=R.getStandings();delta.innerHTML=`<div class="v16section"><b>SECTOR DELTA</b><br><span class="muted">Purple = overall best · Green = personal best · Yellow = slower</span></div><div class="v26delta"><b>P</b><b>DRIVER</b><b>S1</b><b>S2</b><b>S3</b></div>${st.map(c=>{const s=R.sectorTimingFor?.(c.id);return`<div class="v26delta"><b>${c.position}</b><span>${c.name}<br><span class="muted">${String(c.type).toUpperCase()}</span></span>${[0,1,2].map(i=>`<span class="${cls(s?.status?.[i])}">${fmt(s?.last?.[i])}<br><small>PB ${signed(s?.deltaPersonal?.[i])}<br>ALL ${signed(s?.deltaOverall?.[i])}</small></span>`).join('')}</div>`;}).join('')}`;}
  function enhanceControl(){const p=document.getElementById('v24Ctrl');if(!p?.classList.contains('open')||document.getElementById('v26ControlExtra'))return;const c=R.cars[focus]||R.getStandings()[0],pc=R.physicalCaution||{},rec=pc.recoveries||[],reviews=[...(R.incidentReviews||[])].reverse().slice(0,6),cal=R.paceCalibrationFor?.(c?.id);const d=document.createElement('div');d.id='v26ControlExtra';d.innerHTML=`<div class="v16section"><b>PHYSICAL RACE CONTROL</b><br><span class="tag ${pc.type==='SC'||pc.type==='VSC'||pc.type==='RED'?'warn':'good'}">${pc.type||'GREEN'}</span> ${pc.reason||'TRACK CLEAR'}<br><span class="muted">SC count ${pc.scCount||0} · cooldown ${Math.ceil(pc.cooldownRemaining||0)}s · local yellows ${(pc.localYellows||[]).length}</span></div><div class="v16section"><b>RECOVERY</b>${rec.length?rec.map(x=>`<div>${R.cars[x.carId]?.name||'CAR'} · ${x.reason} · ${Math.round(x.progress*100)}%<div class="v26recovery"><i style="width:${Math.round(x.progress*100)}%"></i></div></div>`).join(''):'<br><span class="muted">Track clear. No recovery vehicle active.</span>'}</div><div class="v16section"><b>AUTO PACE CALIBRATION</b><br>${c?.name||'--'} · factor ${cal?.factor?.toFixed?.(3)||'1.000'}<br><span class="muted">Target ${cal?.target?.[0]?cal.target[0].toFixed(1):'--'}–${cal?.target?.[1]?cal.target[1].toFixed(1):'--'}s · 3-lap avg ${cal?.average?cal.average.toFixed(2)+'s':'collecting data'}</span></div><div class="v16section"><b>INCIDENT REVIEW</b>${reviews.length?reviews.map(x=>`<div class="v16section"><b>#${x.id} ${x.type}</b> · S${x.sector}<br>${R.cars[x.carA]?.name||'--'} ${x.speedA} km/h${x.carB!=null?` / ${R.cars[x.carB]?.name||'--'} ${x.speedB} km/h`:''}<br>ΔV ${x.deltaV} km/h · severity ${Math.round(x.severity*100)}% · <span class="warn">${x.caution}</span><br><span class="muted">${x.responsibility}</span></div>`).join(''):'<br><span class="muted">No reviewed incidents.</span>'}</div>`;p.appendChild(d);}

  const map={audioMaster:'master',audioEngine:'engine',audioEffects:'effects',audioRadioVoice:'radioVoice',audioRadioPtt:'radioPtt'};
  function current(){return A?.volumes||readAudioSettings(settings);}
  function soundFields(){return `<div id="v34SoundSettings" class="v24perf"><b>AUDIO</b><div class="setting"><span>Sound</span><select id="setSound"><option value="1">On</option><option value="0">Off</option></select></div><span class="muted">保存して次回起動時にも引き継ぎます。TEST RADIOを押さない限りテスト音声は再生しません。</span></div>`;}
  function mixerHtml(){const v=current(),row=(id,label,key)=>`<div class="setting"><span>${label} <small id="${id}Val">${Math.round(v[key]*100)}%</small></span><input id="${id}" type="range" min="0" max="100" step="1" value="${Math.round(v[key]*100)}"></div>`;return `<div id="runtimeAudioMixer" style="margin-top:8px"><b>MIXER</b>${row('audioMaster','Master','master')}${row('audioEngine','Engine','engine')}${row('audioEffects','Effects','effects')}${row('audioRadioVoice','Radio voice','radioVoice')}${row('audioRadioPtt','Radio PTT','radioPtt')}<span class="muted">各音量も設定と一緒に保存されます。</span></div>`;}
  function enhanceAudio(){const apply=document.getElementById('applySettings');if(apply&&!document.getElementById('v34SoundSettings')){apply.insertAdjacentHTML('beforebegin',soundFields());const e=document.getElementById('setSound');if(e)e.value=settings.sound===false?'0':'1';}const host=document.getElementById('v34SoundSettings');if(host&&!document.getElementById('runtimeAudioMixer'))host.insertAdjacentHTML('beforeend',mixerHtml());}
  function readMixer(){const out={};for(const [id,key] of Object.entries(map)){const e=document.getElementById(id);if(e)out[key]=Math.max(0,Math.min(1,Number(e.value)/100));}return out;}
  function writeSettings(vol){settings.audioMaster=vol.master;settings.audioEngine=vol.engine;settings.audioEffects=vol.effects;settings.audioRadioVoice=vol.radioVoice;settings.audioRadioPtt=vol.radioPtt;}
  drawer.addEventListener('input',e=>{const key=map[e.target?.id];if(!key)return;const val=Math.max(0,Math.min(1,Number(e.target.value)/100)),label=document.getElementById(`${e.target.id}Val`);if(label)label.textContent=`${Math.round(val*100)}%`;const next={...current(),[key]:val};A?.setVolumes?.(next);writeSettings(next);},true);
  drawer.addEventListener('change',e=>{if(!map[e.target?.id])return;const next={...current(),...readMixer()};A?.setVolumes?.(next);writeSettings(next);saveSettings(settings);},true);
  drawer.addEventListener('click',e=>{if(e.target?.id==='applySettings'){const on=document.getElementById('setSound')?.value!=='0';settings.sound=on;A?.setEnabled?.(on);const next={...current(),...readMixer()};A?.setVolumes?.(next);writeSettings(next);saveSettings(settings);}if(e.target?.id==='audioToggle')setTimeout(()=>{settings.sound=!!A?.enabled;saveSettings(settings);const s=document.getElementById('setSound');if(s)s.value=settings.sound?'1':'0';},0);},true);
  const obs=new MutationObserver(enhanceAudio);obs.observe(drawer,{subtree:true,childList:true});enhanceAudio();

  const oldUpdate=base.update;
  return new Proxy(base,{get(target,prop){if(prop==='update')return(dt,id)=>{focus=Number(id)||0;oldUpdate(dt,id);acc+=dt;if(acc>=.5){acc=0;if(radarOpen)renderRadar();if(deltaOpen)renderDelta();enhanceControl();enhanceAudio();}};return Reflect.get(target,prop,target);}});
}
