import {buildWorld as buildV15World} from './v15-world.js';

export function buildWorld(THREE,TRACK,settings={},circuitName='SUZUKA'){
  const W=buildV15World(THREE,TRACK,settings,circuitName),root=new THREE.Group();root.name='V16_WORLD';W.scene.add(root);
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),wrapS=s=>((s%W.total)+W.total)%W.total;
  const lineMat=new THREE.MeshPhysicalMaterial({color:0x141719,roughness:.54,metalness:.05,transparent:true,opacity:.10,depthWrite:false,side:THREE.DoubleSide});
  const seg=420,pos=[],ind=[];
  for(let i=0;i<seg;i++){const s=W.total*i/seg,q=W.sample(s),curveA=W.sample(s-18).t,curveB=W.sample(s+18).t,cross=curveA.x*curveB.z-curveA.z*curveB.x,off=clamp(cross*7.5,-1.35,1.35),c=q.p.clone().addScaledVector(q.side,off),l=c.clone().addScaledVector(q.side,-1.35),r=c.clone().addScaledVector(q.side,1.35);l.y+=.083;r.y+=.083;pos.push(l.x,l.y,l.z,r.x,r.y,r.z);}
  for(let i=0;i<seg;i++){const j=(i+1)%seg,a=i*2,b=a+1,c=j*2,d=c+1;ind.push(a,b,c,b,d,c);}const lg=new THREE.BufferGeometry();lg.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));lg.setIndex(ind);lg.computeVertexNormals();const racingLine=new THREE.Mesh(lg,lineMat);racingLine.renderOrder=3;root.add(racingLine);
  const surface={rubber:.08,dryLine:0,wetness:0};
  const puddleDefs=[[.135,-2.1,7.5],[.318,2.4,6.2],[.505,-1.6,7.0],[.735,2.2,6.6],[.872,-2.5,7.8]],puddles=[];
  const puddleMat=new THREE.MeshPhysicalMaterial({color:0x667b89,roughness:.06,metalness:.12,transparent:true,opacity:0,depthWrite:false,side:THREE.DoubleSide,envMapIntensity:1.4});
  for(const [f,off,r] of puddleDefs){const q=W.sample(W.total*f,off),m=new THREE.Mesh(new THREE.CircleGeometry(r,28),puddleMat.clone());m.rotation.x=-Math.PI/2;m.position.copy(q.p);m.position.y+=.095;m.scale.z=.38;m.userData={s:W.total*f,offset:off,radius:r};root.add(m);puddles.push(m);}
  function particlePool(count,material){const a=new Float32Array(count*3);for(let i=0;i<count;i++)a[i*3+1]=-999;const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(a,3));const p=new THREE.Points(g,material);p.frustumCulled=false;root.add(p);return{p,a,life:new Float32Array(count),vel:Array.from({length:count},()=>new THREE.Vector3()),cursor:0};}
  const spray=particlePool(180,new THREE.PointsMaterial({color:0xddeeff,size:1.05,transparent:true,opacity:.34,depthWrite:false,sizeAttenuation:true}));
  const smoke=particlePool(100,new THREE.PointsMaterial({color:0xe5e5e5,size:1.25,transparent:true,opacity:.30,depthWrite:false,sizeAttenuation:true}));
  function spawn(pool,p,v,life){const i=pool.cursor++%pool.life.length;pool.a[i*3]=p.x;pool.a[i*3+1]=p.y;pool.a[i*3+2]=p.z;pool.life[i]=life;pool.vel[i].copy(v);}
  function stepPool(pool,dt){for(let i=0;i<pool.life.length;i++){if(pool.life[i]<=0)continue;pool.life[i]-=dt;pool.a[i*3]+=pool.vel[i].x*dt;pool.a[i*3+1]+=pool.vel[i].y*dt;pool.a[i*3+2]+=pool.vel[i].z*dt;if(pool.life[i]<=0)pool.a[i*3+1]=-999;}pool.p.geometry.attributes.position.needsUpdate=true;}
  const debris=[];const carbon=new THREE.MeshStandardMaterial({color:0x111416,metalness:.28,roughness:.38});
  W.spawnDebris=(car,count=5)=>{if(!car)return;const zone={id:`deb-${Date.now()}-${Math.random()}`,s:car.s,lane:car.lane,age:0,radius:10,hit:new Set(),objs:[]};for(let i=0;i<count;i++){const q=W.sample(wrapS(car.s+(Math.random()-.5)*11),car.lane+(Math.random()-.5)*4),m=new THREE.Mesh(new THREE.BoxGeometry(.18+Math.random()*.34,.025+Math.random()*.05,.20+Math.random()*.42),carbon);m.position.copy(q.p);m.position.y+=.12;m.rotation.set(Math.random(),Math.random()*Math.PI,Math.random());root.add(m);zone.objs.push(m);}debris.push(zone);return zone;};
  W.updateDebris=dt=>{for(let i=debris.length-1;i>=0;i--){const z=debris[i];z.age+=dt;for(const o of z.objs)o.rotation.y+=dt*.35;if(z.age>24){for(const o of z.objs)root.remove(o);debris.splice(i,1);}}};Object.defineProperty(W,'debrisZones',{get:()=>debris});
  W.updateDynamicSurface=(race,wetness=0,dt=.016)=>{surface.wetness=wetness;surface.rubber=clamp(surface.rubber+dt*(wetness<.25?.0009:.00018),0,1);surface.dryLine=clamp(surface.rubber*(1-wetness*.72),0,1);lineMat.opacity=.07+surface.rubber*.18+wetness*.05;lineMat.roughness=clamp(.60-wetness*.24-surface.rubber*.05,.22,.62);for(const p of puddles){const local=clamp((wetness-.30)/.55,0,1);p.material.opacity=local*.38;p.visible=local>.02;}};
  W.getHydroRisk=car=>{const wet=W.env?.wetness||surface.wetness||0;if(wet<.42||!car)return 0;let risk=0;for(const p of puddles){let ds=Math.abs(wrapS(car.s-p.userData.s));ds=Math.min(ds,W.total-ds);const dl=Math.abs((car.lane||0)-p.userData.offset);if(ds<p.userData.radius*1.6&&dl<p.userData.radius*.58){const closeness=(1-ds/(p.userData.radius*1.6))*(1-dl/(p.userData.radius*.58));risk=Math.max(risk,closeness*wet);}}return clamp(risk,0,1);};W.surfaceState=surface;
  W.updateEffects=(cars=[],dt=.016)=>{const wet=W.env?.wetness||0;for(const c of cars){if(c.retired||!c.mesh?.visible)continue;const q=W.sample(c.s,c.lane),back=c.mesh.position.clone().addScaledVector(q.t,-2.0);if(wet>.25&&c.v>18){const n=c.v>45?2:1;for(let k=0;k<n;k++){const p=back.clone().addScaledVector(q.side,(Math.random()-.5)*1.5).add(new THREE.Vector3(0,.35+Math.random()*.25,0)),v=q.t.clone().multiplyScalar(-5-Math.random()*5);v.y=1.2+Math.random()*1.2;v.addScaledVector(q.side,(Math.random()-.5)*2);spawn(spray,p,v,.65+Math.random()*.45);}}if((c.brakeVisual||0)>.88&&c.v>22){const p=back.clone().add(new THREE.Vector3(0,.25,0)),v=q.t.clone().multiplyScalar(-2.2);v.y=.7;v.addScaledVector(q.side,(Math.random()-.5)*1.5);spawn(smoke,p,v,.75);}}stepPool(spray,dt);stepPool(smoke,dt);};
  const podium=new THREE.Group();podium.visible=false;root.add(podium);const pq=W.sample(W.total*.018,29),ang=Math.atan2(pq.t.x,pq.t.z);podium.position.copy(pq.p);podium.rotation.y=ang;
  const stageM=new THREE.MeshStandardMaterial({color:0xeeeeea,roughness:.65}),gold=new THREE.MeshStandardMaterial({color:0xe3bc35,metalness:.25,roughness:.45}),silver=new THREE.MeshStandardMaterial({color:0xaeb7bd,metalness:.35,roughness:.35}),bronze=new THREE.MeshStandardMaterial({color:0xa96b38,metalness:.30,roughness:.4});
  const boxes=[[0,1.15,0,gold,1],[-1.2,.82,.25,silver,2],[1.2,.66,.35,bronze,3]],podiumPeople=[];
  for(const [x,h,z,m,n] of boxes){const b=new THREE.Mesh(new THREE.BoxGeometry(1.05,h,.95),m);b.position.set(x,h/2,z);podium.add(b);const c=document.createElement('canvas');c.width=96;c.height=96;const g=c.getContext('2d');g.fillStyle='#111';g.fillRect(0,0,96,96);g.fillStyle='#fff';g.font='900 62px sans-serif';g.textAlign='center';g.textBaseline='middle';g.fillText(String(n),48,50);const tex=new THREE.CanvasTexture(c),sign=new THREE.Mesh(new THREE.PlaneGeometry(.48,.48),new THREE.MeshBasicMaterial({map:tex}));sign.position.set(x,h*.55,z+.49);podium.add(sign);const p=new THREE.Group(),body=new THREE.Mesh(new THREE.BoxGeometry(.34,.62,.24),stageM),head=new THREE.Mesh(new THREE.SphereGeometry(.15,8,6),new THREE.MeshStandardMaterial({color:0xd0a07a}));body.position.y=.46;head.position.y=.91;p.add(body,head);p.position.set(x,h,z);podium.add(p);podiumPeople.push(p);}
  const champagne=particlePool(90,new THREE.PointsMaterial({color:0xf4f8ff,size:.19,transparent:true,opacity:.8,depthWrite:false}));
  W.updatePostRace=(stage='NONE',top3=[],dt=.016)=>{podium.visible=['PARC_FERME','PODIUM','CHAMPAGNE'].includes(stage);if(stage==='CHAMPAGNE'){for(let k=0;k<3;k++){const p=podiumPeople[k];if(!p)continue;const wp=new THREE.Vector3();p.getWorldPosition(wp);for(let j=0;j<2;j++){const v=new THREE.Vector3((Math.random()-.5)*2.4,3.5+Math.random()*2,(Math.random()-.5)*2.2);spawn(champagne,wp.clone().add(new THREE.Vector3(0,1.0,0)),v,1.0+Math.random()*.6);}}}stepPool(champagne,dt);};
  return W;
}
